BEGIN;

CREATE TABLE inventories (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    ip INET NOT NULL,
    search_idx TSVECTOR NOT NULL,
    attributes HSTORE NULL,
    mac MACADDR NOT NULL
);

CREATE INDEX inventories_search_idx_gin ON inventories USING gin (search_idx);
CREATE INDEX inventories_payload_gin ON inventories USING gin (payload jsonb_path_ops);

COMMENT ON TABLE inventories IS 'Grand-tour inventory — exercises PG-specific types via the D36
custom_types registry (HSTORE through alias "hstore", MACADDR
through alias "pg_macaddr"), plus core Types for JSON / IP /
TSEARCH (lifted into field.Type by D13). Our test-apply harness
installs hstore per DB so the fixture applies on stock
postgres:18-alpine.';

COMMIT;
