BEGIN;

CREATE TABLE inventories (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    ip INET NOT NULL,
    search_idx TSVECTOR NOT NULL,
    attributes HSTORE NULL,
    mac MACADDR NOT NULL
);

CREATE INDEX inventories_search_idx_gin ON inventories USING gin (search_idx);
CREATE INDEX inventories_payload_gin ON inventories USING gin (payload jsonb_path_ops);

COMMIT;
