BEGIN;

CREATE TABLE events (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    subject VARCHAR(200) NOT NULL,
    external_id VARCHAR(64) NOT NULL,
    CONSTRAINT events_subject_blank CHECK (subject <> ''),
    CONSTRAINT events_external_id_blank CHECK (external_id <> '')
);

CREATE INDEX events_timeline_idx ON events (occurred_at DESC NULLS LAST, id);
CREATE INDEX events_subject_prefix_idx ON events (subject text_pattern_ops);
CREATE INDEX events_subject_trgm_gin ON events USING gin (subject gin_trgm_ops);
CREATE INDEX events_occurred_brin ON events USING brin (occurred_at) WITH (autosummarize=on, pages_per_range=32);
CREATE INDEX events_external_id_hash ON events USING hash (external_id);

COMMIT;
