BEGIN;

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address JSONB NOT NULL,
    pb_meta BYTEA NOT NULL,
    billing_addr JSONB NULL
);

COMMENT ON COLUMN users.address IS 'Default JSONB — queryable via PG JSON operators.';
COMMENT ON COLUMN users.pb_meta IS 'PbBytes path — author serialises proto.Marshal bytes; compiler
emits BYTEA column. Opaque binary storage, compact, not
queryable at the column level.';
COMMENT ON COLUMN users.billing_addr IS 'Nullable message field.';

COMMIT;
