BEGIN;

CREATE TABLE products (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL,
    title VARCHAR(200) NOT NULL,
    homepage VARCHAR(2048) NOT NULL,
    discount NUMERIC(5, 2) NOT NULL,
    sold BIGINT NOT NULL,
    launch_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT products_slug_blank CHECK (slug <> ''),
    CONSTRAINT products_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT products_title_blank CHECK (title <> ''),
    CONSTRAINT products_homepage_blank CHECK (homepage <> ''),
    CONSTRAINT products_homepage_format CHECK (homepage ~ '^https?://.+$'),
    CONSTRAINT products_discount_range CHECK (discount BETWEEN 0 AND 75)
);

CREATE UNIQUE INDEX products_slug_uidx ON products (slug);

COMMENT ON TABLE products IS 'Golden: single-table schema focused on types the happy fixture barely
covers — SLUG (regex), URL (regex), DATE with CURRENT_DATE default,
PERCENTAGE with author-supplied bounds, COUNTER.

UUID pk and DECIMAL are deliberately NOT used here: both are
string-carrier in IR (so the blank-check synth fires) but render as
non-string SQL types (UUID / NUMERIC), so the emitted `CHECK (col <>
'''')` would fail at apply time. That''s a pipeline gap — see
docs/iteration-1-impl.md "Known gaps" — not something the golden
should canonise.';

COMMIT;
