BEGIN;

CREATE TABLE priorities (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight SMALLINT NOT NULL,
    rank SMALLINT NOT NULL,
    ordinals SMALLINT[] NOT NULL,
    CONSTRAINT priorities_rank_range CHECK (rank BETWEEN 1 AND 10)
);

COMMENT ON COLUMN priorities.weight IS 'Bare SMALL_INTEGER — no range bound, storage SMALLINT NOT NULL.';
COMMENT ON COLUMN priorities.rank IS 'With bounded range. CHECK emits like any other numeric range.';
COMMENT ON COLUMN priorities.ordinals IS 'repeated scalar + SMALL_INTEGER — SMALLINT[] storage via
element-level dispatch in pgArrayOf.';

COMMIT;
