BEGIN;

CREATE TABLE user_profiles (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    CONSTRAINT user_profiles_email_blank CHECK (email <> ''),
    CONSTRAINT user_profiles_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

CREATE UNIQUE INDEX user_profiles_email_uidx ON user_profiles (email);

CREATE TABLE admin_extras (
    profile_id BIGINT NOT NULL PRIMARY KEY REFERENCES user_profiles(id) ON DELETE CASCADE,
    permissions JSONB NOT NULL
);

COMMIT;
