BEGIN;

CREATE TABLE events (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(64) NOT NULL,
    payload TEXT NOT NULL,
    CONSTRAINT events_kind_blank CHECK (kind <> '')
);

COMMENT ON TABLE events IS 'Golden: minimal table with no indexes of any flavour — no unique, no
(w17.db.column).index, no (w17.db.table).indexes, no FK. Exercises the
"up has no CREATE INDEX / down has no DROP INDEX" branch of emission.';

COMMIT;
