BEGIN;

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    full_name VARCHAR(200) NOT NULL GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
    CONSTRAINT users_first_name_blank CHECK (first_name <> ''),
    CONSTRAINT users_last_name_blank CHECK (last_name <> ''),
    CONSTRAINT users_full_name_blank CHECK (full_name <> '')
);

CREATE INDEX users_full_name_idx ON users (full_name);

COMMIT;
