BEGIN;

CREATE TABLE sessions (
    id BIGINT NOT NULL PRIMARY KEY,
    payload TEXT NOT NULL,
    CONSTRAINT sessions_payload_blank CHECK (payload <> '')
);

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT users_name_blank CHECK (name <> ''),
    CONSTRAINT users_email_blank CHECK (email <> ''),
    CONSTRAINT users_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

CREATE UNIQUE INDEX users_email_uidx ON users (email);

COMMIT;
