BEGIN;

CREATE TABLE customers (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT customers_name_blank CHECK (name <> ''),
    CONSTRAINT customers_email_blank CHECK (email <> ''),
    CONSTRAINT customers_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

CREATE UNIQUE INDEX customers_email_uidx ON customers (email);

COMMENT ON TABLE customers IS 'File A — customers table. No module namespace (defaults to public
on PG). File B (orders.proto) references this table by name.';

CREATE TABLE orders (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    total NUMERIC(19, 4) NOT NULL
);

COMMENT ON TABLE orders IS 'File B — orders table with an FK into customers (defined in
customers.proto). Cross-file FK resolution is M2''s job; same-
import-path-set means the compiled batch sees both files.';

COMMIT;
