BEGIN;

CREATE TABLE bookings (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    price NUMERIC(19, 4) NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT bookings_email_blank CHECK (email <> ''),
    CONSTRAINT bookings_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    CONSTRAINT bookings_customer_name_blank CHECK (customer_name <> ''),
    CONSTRAINT bookings_price_range CHECK (price >= 0),
    CONSTRAINT bookings_dates_ordered CHECK (start_at <= end_at),
    CONSTRAINT bookings_price_cents CHECK ((price * 100) = floor(price * 100))
);

CREATE UNIQUE INDEX bookings_email_active_uidx ON bookings (email) WHERE deleted_at IS NULL;
CREATE INDEX bookings_lower_customer_idx ON bookings (lower(customer_name));

COMMIT;
