BEGIN;

CREATE TABLE articles (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notes TEXT NOT NULL,
    visits INTEGER NOT NULL,
    archived BOOLEAN NOT NULL,
    bio TEXT NOT NULL,
    email CITEXT NOT NULL,
    text_config JSON NOT NULL DEFAULT '{}',
    counter BIGINT NOT NULL,
    raw_payload JSONB NOT NULL,
    external_uuid UUID NOT NULL,
    custom_rate NUMERIC(12, 4) NOT NULL,
    priority SMALLINT NOT NULL,
    client_ip INET NOT NULL,
    CONSTRAINT articles_bio_len CHECK (char_length(bio) <= 6000),
    CONSTRAINT articles_bio_blank CHECK (bio <> ''),
    CONSTRAINT articles_email_blank CHECK (email <> ''),
    CONSTRAINT articles_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

CREATE UNIQUE INDEX articles_email_uidx ON articles (email);

COMMENT ON TABLE articles IS 'Grand-tour fixture for D14 — field.Type (data semantic) and
(w17.db.column).db_type (storage) as orthogonal axes. Exercises:

  - CHAR validation + TEXT storage: bio keeps char_length CHECK <= 6000
    (storage isn''t VARCHAR-backed so the length CHECK is not subsumed)
    but renders as TEXT.
  - EMAIL validation + CITEXT storage: email keeps the format regex
    + blank CHECK, renders as CITEXT so UNIQUE INDEX is case-
    insensitive without extra WHERE clauses.
  - JSON vs JSONB explicit: text_config forces JSON (whitespace-
    preserving, not indexed) instead of the preset''s JSONB default.
  - int64 NUMBER default + BIGINT storage override (explicit even
    though it matches the preset — regression guard that unchanged
    semantics still flow through the db_type path).
  - Zero-config columns exercise D14 per-carrier defaults: `notes`
    is bare `string` → TEXT, `visits` is bare `int32` → INTEGER,
    `archived` is bare `bool` → BOOLEAN.';
COMMENT ON COLUMN articles.notes IS 'Zero-config — no (w17.field), default TEXT / INTEGER / BOOLEAN.';
COMMENT ON COLUMN articles.bio IS 'Data semantic + storage override: CHAR(6000) char_length CHECK, TEXT storage.';
COMMENT ON COLUMN articles.email IS 'EMAIL validation (regex + blank), CITEXT storage.';
COMMENT ON COLUMN articles.text_config IS 'JSON semantic, text-stored JSON (not JSONB).';
COMMENT ON COLUMN articles.counter IS 'Redundant-but-explicit: BIGINT via db_type even though default is BIGINT.';
COMMENT ON COLUMN articles.raw_payload IS 'JSONB via explicit db_type on bytes carrier — bytes + JSONB is a
legitimate iter-1 combination (bytes carry the serialised JSON
payload; PG stores as JSONB for querying).';
COMMENT ON COLUMN articles.external_uuid IS 'UUID storage override on string carrier — stays UUID at SQL level
even though the data semantic is free-form string.';
COMMENT ON COLUMN articles.custom_rate IS 'NUMERIC via db_type on DECIMAL sem — storage override equals the
sem default but exercises the NUMERIC-requires-precision branch
in validateDbType.';
COMMENT ON COLUMN articles.priority IS 'SMALLINT via db_type (D22c provides SMALL_INTEGER preset; db_type
is the equivalent storage-level override path).';
COMMENT ON COLUMN articles.client_ip IS 'INET on string carrier via db_type override — cross-dialect enum
form; distinct from the TEXT+custom_type path.';

COMMIT;
