BEGIN;

CREATE TABLE articles (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notes TEXT NOT NULL,
    visits INTEGER NOT NULL,
    archived BOOLEAN NOT NULL,
    bio TEXT NOT NULL,
    email CITEXT NOT NULL,
    text_config JSON NOT NULL DEFAULT '{}',
    counter BIGINT NOT NULL,
    CONSTRAINT articles_bio_len CHECK (char_length(bio) <= 6000),
    CONSTRAINT articles_bio_blank CHECK (bio <> ''),
    CONSTRAINT articles_email_blank CHECK (email <> ''),
    CONSTRAINT articles_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

CREATE UNIQUE INDEX articles_email_uidx ON articles (email);

COMMIT;
