BEGIN;

CREATE TABLE devices (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wired_mac MACADDR NOT NULL,
    spare_mac VARCHAR(17) NULL,
    CONSTRAINT devices_spare_mac_format CHECK (spare_mac ~ '^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$')
);

COMMENT ON TABLE devices IS 'D22b fixture — MAC_ADDRESS preset on string carrier. Exercises:
  (a) default path → PG MACADDR native storage, no regex CHECK
      (native type enforces format on INSERT/UPDATE),
  (b) db_type: VARCHAR override → VARCHAR(17) storage, regex
      CHECK + blank CHECK synthesised automatically ("max
      defensibility" when the native type isn''t in play).';
COMMENT ON COLUMN devices.wired_mac IS 'Native MACADDR storage — PG type enforces format; no regex/blank.';
COMMENT ON COLUMN devices.spare_mac IS 'VARCHAR(17) storage — regex + blank CHECKs synthesise; max_len
default of 17 fits the xx:xx:xx:xx:xx:xx form.';

COMMIT;
