BEGIN;

CREATE TABLE catalog_categories (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT catalog_categories_name_blank CHECK (name <> '')
);

CREATE UNIQUE INDEX catalog_categories_name_uidx ON catalog_categories (name);

CREATE TABLE catalog_products (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES catalog_categories(id) ON DELETE RESTRICT,
    sku VARCHAR(40) NOT NULL,
    status INTEGER NOT NULL,
    price NUMERIC(19, 4) NOT NULL,
    CONSTRAINT catalog_products_sku_blank CHECK (sku <> ''),
    CONSTRAINT catalog_products_status_choices CHECK (status IN (1, 2, 3)),
    CONSTRAINT catalog_price_non_negative CHECK (price >= 0)
);

CREATE INDEX catalog_by_category ON catalog_products (category_id);
CREATE UNIQUE INDEX catalog_products_sku_uidx ON catalog_products (sku);

COMMIT;
