BEGIN;

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(32) NOT NULL,
    handle VARCHAR(64) NOT NULL,
    CONSTRAINT users_email_blank CHECK (email <> ''),
    CONSTRAINT users_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    CONSTRAINT users_username_blank CHECK (username <> ''),
    CONSTRAINT users_handle_blank CHECK (handle <> ''),
    CONSTRAINT users_handle_format CHECK (handle ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE UNIQUE INDEX users_tenant_handle_uidx ON users (tenant_id, handle);
CREATE UNIQUE INDEX users_tenant_email_cover_uidx ON users (tenant_id, email) INCLUDE (username);
CREATE UNIQUE INDEX users_username_explicit_uidx ON users (username);
CREATE UNIQUE INDEX users_email_uidx ON users (email);

COMMENT ON TABLE users IS 'Golden: three uniqueness sources on one table — two single-column
(w17.field).unique synths (email, username) plus one named multi-column
UNIQUE table-level index (tenant_id, handle). Covers synth ordering,
derived vs. explicit index names, and reverse DROP INDEX in down.';

COMMIT;
