BEGIN;

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    email VARCHAR(320) NOT NULL,
    username VARCHAR(32) NOT NULL,
    handle VARCHAR(64) NOT NULL,
    CONSTRAINT users_email_len CHECK (char_length(email) <= 255),
    CONSTRAINT users_email_blank CHECK (email <> ''),
    CONSTRAINT users_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    CONSTRAINT users_username_blank CHECK (username <> ''),
    CONSTRAINT users_handle_blank CHECK (handle <> ''),
    CONSTRAINT users_handle_format CHECK (handle ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE UNIQUE INDEX users_tenant_handle_uidx ON users (tenant_id, handle);
CREATE UNIQUE INDEX users_email_uidx ON users (email);
CREATE UNIQUE INDEX users_username_uidx ON users (username);

COMMIT;
