BEGIN;

CREATE TABLE articles (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    byline VARCHAR(100) NOT NULL,
    view_count BIGINT NOT NULL,
    email VARCHAR(320) NOT NULL,
    CONSTRAINT articles_title_blank CHECK (title <> ''),
    CONSTRAINT articles_byline_blank CHECK (byline <> ''),
    CONSTRAINT articles_email_blank CHECK (email <> ''),
    CONSTRAINT articles_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

CREATE INDEX articles_byline_idx ON articles (byline);

COMMENT ON TABLE articles IS 'Published article visible to subscribers.
Rows are immutable once published — use archive_at for soft delete.';
COMMENT ON COLUMN articles.id IS 'Primary key, auto-incrementing.';
COMMENT ON COLUMN articles.title IS 'Visible article title; shouldn''t exceed 200 characters.';
COMMENT ON COLUMN articles.byline IS 'Author''s byline, e.g. "Jane''s commentary". Also exercises:
  - (w17.db.column).index on a non-FK column (storage-index synth)';
COMMENT ON COLUMN articles.email IS 'Column rename via (w17.db.column).name — the SQL column is
`email` even though the proto field is `email_address`. Positive
counterpart to the default_name_reserved error fixture.';

CREATE TABLE subscribers (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    CONSTRAINT subscribers_email_blank CHECK (email <> ''),
    CONSTRAINT subscribers_email_format CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

CREATE UNIQUE INDEX subscribers_email_uidx ON subscribers (email);

COMMENT ON TABLE subscribers IS 'Email recipients for published articles.';

COMMIT;
