CREATE TABLE measurements (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading INTEGER NOT NULL,
    code INTEGER NOT NULL,
    hits BIGINT NOT NULL,
    raw DOUBLE PRECISION NOT NULL,
    price NUMERIC(19, 4) NOT NULL,
    conversion NUMERIC(5, 4) NOT NULL,
    exact_amount NUMERIC(18, 6) NOT NULL,
    CONSTRAINT measurements_reading_range CHECK (reading > -50 AND reading < 50),
    CONSTRAINT measurements_raw_range CHECK (raw BETWEEN 0 AND 1e+06),
    CONSTRAINT measurements_conversion_range CHECK (conversion BETWEEN 0 AND 1)
);
