BEGIN;

CREATE TABLE reporting.dashboards (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    CONSTRAINT dashboards_title_blank CHECK (title <> '')
);

CREATE UNIQUE INDEX dashboards_title_uidx ON reporting.dashboards (title);

CREATE TABLE reporting.widgets (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashboard_id BIGINT NOT NULL REFERENCES reporting.dashboards(id) ON DELETE CASCADE,
    kind VARCHAR(40) NOT NULL,
    CONSTRAINT widgets_kind_blank CHECK (kind <> '')
);

CREATE INDEX widgets_dashboard_id_kind_idx ON reporting.widgets (dashboard_id, kind);

COMMIT;
