BEGIN;

CREATE TABLE flags (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    tags_json TEXT NOT NULL DEFAULT '[]',
    config_json TEXT NOT NULL DEFAULT '{}',
    visibility VARCHAR(16) NOT NULL,
    callsign VARCHAR(8) NOT NULL,
    CONSTRAINT flags_tags_json_blank CHECK (tags_json <> ''),
    CONSTRAINT flags_config_json_blank CHECK (config_json <> ''),
    CONSTRAINT flags_visibility_blank CHECK (visibility <> ''),
    CONSTRAINT flags_visibility_choices CHECK (visibility IN ('DRAFT', 'PRIVATE', 'PUBLIC')),
    CONSTRAINT flags_callsign_blank CHECK (callsign <> ''),
    CONSTRAINT flags_callsign_format CHECK (callsign ~ '^[A-Z][A-Z0-9]{2,7}$')
);

COMMIT;
