BEGIN;

CREATE TABLE tickets (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority INTEGER NOT NULL,
    severity BIGINT NOT NULL,
    channel INTEGER NOT NULL,
    CONSTRAINT tickets_priority_choices CHECK (priority IN (1, 2, 3)),
    CONSTRAINT tickets_severity_choices CHECK (severity IN (10, 20, 30)),
    CONSTRAINT tickets_channel_choices CHECK (channel IN (1, 2, 3))
);

COMMENT ON COLUMN tickets.channel IS 'Reference to the nested enum by its FQN — `d17.enum_int_backed
.Ticket.Channel`. Exercises recursive walk through Messages().';

COMMIT;
