BEGIN;

CREATE TABLE tickets (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority INTEGER NOT NULL,
    severity BIGINT NOT NULL,
    CONSTRAINT tickets_priority_choices CHECK (priority IN (1, 2, 3)),
    CONSTRAINT tickets_severity_choices CHECK (severity IN (10, 20, 30))
);

COMMIT;
