BEGIN;

CREATE TABLE categories (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NULL REFERENCES categories(id) ON DELETE SET NULL,
    root_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT categories_name_blank CHECK (name <> '')
);

COMMENT ON COLUMN categories.root_id IS 'Second self-ref FK with BLOCK on a non-null column — pairs with
the ORPHAN ref above to exercise self-FK × every deletion_rule.';

CREATE TABLE customers (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT customers_name_blank CHECK (name <> '')
);

CREATE TABLE orders (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    assigned_to BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL,
    auditor_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    fulfilled_by_id BIGINT NOT NULL DEFAULT 0 REFERENCES customers(id) ON DELETE SET DEFAULT,
    status VARCHAR(16) NOT NULL,
    total NUMERIC(19, 4) NOT NULL,
    CONSTRAINT orders_status_blank CHECK (status <> '')
);

CREATE INDEX orders_customer_id_status_idx ON orders (customer_id, status) INCLUDE (total);
CREATE INDEX orders_assigned_to_explicit_idx ON orders (assigned_to);

COMMIT;
