CREATE TABLE categories (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NULL REFERENCES categories(id) ON DELETE SET NULL,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT categories_name_blank CHECK (name <> '')
);

CREATE TABLE customers (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT customers_name_blank CHECK (name <> '')
);

CREATE TABLE orders (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    assigned_to BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL,
    status VARCHAR(16) NOT NULL,
    total NUMERIC(19, 4) NOT NULL,
    CONSTRAINT orders_status_blank CHECK (status <> '')
);

CREATE INDEX orders_customer_id_status_idx ON orders (customer_id, status) INCLUDE (total);
CREATE INDEX orders_assigned_to_idx ON orders (assigned_to);
