package postgres

import "github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/emit"

// pgCatalog maps every capability the Postgres emitter may reference
// to its target-DB requirements. Version numbers are PG releases
// (dotted-decimal, no "v" prefix); extension names match pg_catalog
// naming.
//
// To add a capability: add the constant in emit/capabilities.go,
// add an entry here, reference the constant wherever the emitter
// uses the feature. Tests ensure every referenced cap is in the
// catalog.
//
// Version sources — PostgreSQL release notes for each feature:
//   gen_random_uuid() built-in:        PG 13 (earlier: pgcrypto)
//   uuidv7() built-in:                 PG 18 (earlier: pg_uuidv7)
//   GENERATED BY DEFAULT AS IDENTITY:  PG 10 (SQL:2003)
//   INCLUDE (covering index):          PG 11
//   GENERATED ALWAYS AS … STORED:      PG 12 (SQL:2016)
//   JSONB:                             PG 9.4
//   JSON:                              PG 9.2
//   TIMESTAMPTZ:                       PG 7.3 (rename from TIMESTAMP WITH TIME ZONE)
//   UUID native type:                  PG 8.3
//   TSVECTOR:                          PG 8.3
//   jsonb_path_ops opclass:            PG 9.5
//   Partial / expression indexes:      PG 7.4
//   Transactional DDL:                 PG 7.3 (every CREATE TABLE etc.)
//
// Iter-1 implicit floor: PG 14 (AC #2). Most features predate this
// comfortably; uuidv7() is the only one that requires 18+. Iter-2
// will parameterise target and validate actively.
var pgCatalog = map[string]emit.Requirement{
	// Core SQL types.
	emit.CapJSON:             {MinVersion: "9.2"},
	emit.CapJSONB:            {MinVersion: "9.4"},
	emit.CapDate:             {},
	emit.CapTime:             {},
	emit.CapTimestamp:        {},
	emit.CapTimestampTZ:      {MinVersion: "7.3"},
	emit.CapInterval:         {},
	emit.CapNumeric:          {},
	emit.CapDoublePrecision:  {},
	emit.CapUUID:             {MinVersion: "8.3"},
	emit.CapBYTEA:            {},
	emit.CapBoolean:          {},
	emit.CapArray:            {MinVersion: "7.4"},
	// CREATE TYPE <name> AS ENUM (…) landed in PostgreSQL 8.3
	// alongside the broader enum feature; earlier versions have no
	// dedicated enumerated type (compiler dispatches to VARCHAR +
	// CHECK IN names on those targets).
	emit.CapEnumType: {MinVersion: "8.3"},
	// Schema-qualified identifiers (<schema>.<table>) have been
	// available on every PG release we support; no minimum version.
	emit.CapSchemaQualified: {},
	// COMMENT ON TABLE / COLUMN — SQL:1999 feature, present in every
	// PG release we support.
	emit.CapCommentOn: {},

	// Index access methods (D23). BTREE is PG's default and always
	// available (no cap). Non-BTREE methods have per-version release
	// floors:
	//   GIN    — PG 8.2 (contrib in 7.4, core in 8.2)
	//   GIST   — PG 8.1 (core since 7.1; modern shape since 8.1)
	//   BRIN   — PG 9.5 (new in 9.5, no earlier variant)
	//   SPGIST — PG 9.2 (new in 9.2)
	//   HASH   — PG 10 (crash-safe / WAL-logged since 10; earlier
	//            releases had HASH but couldn't replicate or survive
	//            crashes, effectively unusable in production)
	emit.CapGinIndex:    {MinVersion: "8.2"},
	emit.CapGistIndex:   {MinVersion: "8.1"},
	emit.CapBrinIndex:   {MinVersion: "9.5"},
	emit.CapSpgistIndex: {MinVersion: "9.2"},
	emit.CapHashIndex:   {MinVersion: "10.0"},

	// Index + constraint features.
	emit.CapIncludeIndex:       {MinVersion: "11.0"},
	emit.CapPartialIndex:       {MinVersion: "7.4"},
	emit.CapExpressionIndex:    {MinVersion: "7.4"},
	emit.CapIdentityColumn:     {MinVersion: "10.0"},
	// GENERATED ALWAYS AS (expr) STORED landed in PostgreSQL 12 (the
	// SQL:2016 feature); PG 11 and earlier have no STORED-generated-
	// column support (only expression indexes / views replicate part of
	// the shape).
	emit.CapGeneratedColumn:    {MinVersion: "12.0"},
	emit.CapOnDeleteRestrict:   {},
	emit.CapOnDeleteSetDefault: {},

	// Transactional DDL.
	emit.CapTransactionalDDL: {},

	// Postgres-specific types.
	emit.CapINET:     {},
	emit.CapCIDR:     {},
	emit.CapMACADDR:  {},
	emit.CapTSVECTOR: {MinVersion: "8.3"},
	emit.CapTSQUERY:  {MinVersion: "8.3"},

	// Postgres-specific functions + opclasses.
	emit.CapFnGenRandomUUID: {MinVersion: "13.0"},
	// uuidv7() is built into PG 18+; older majors need the pg_uuidv7
	// extension. We model MinVersion (the easiest target) and let the
	// extension path land alongside multi-version config in iter-2.
	emit.CapFnUUIDv7:       {MinVersion: "18.0"},
	emit.CapOpJsonbPathOps: {MinVersion: "9.5"},
	emit.CapOpGinTrgmOps:   {Extensions: []string{emit.CapExtPgTrgm}},

	// Extensions. MinVersion on extensions is the version the
	// extension started shipping with; iter-1 ignores this (extensions
	// are assumed loaded via required_extensions).
	emit.CapExtHstore:       {Extensions: []string{emit.CapExtHstore}},
	emit.CapExtCitext:       {Extensions: []string{emit.CapExtCitext}},
	emit.CapExtPgTrgm:       {Extensions: []string{emit.CapExtPgTrgm}},
	emit.CapExtPgJsonschema: {Extensions: []string{emit.CapExtPgJsonschema}},
	emit.CapExtPgUUIDv7:     {Extensions: []string{emit.CapExtPgUUIDv7}},
}

// Name returns the stable dialect identifier. Matches DialectEmitter.
// Already defined on Emitter in emit.go; this file adds the
// DialectCapabilities surface.
//
// Requirement implements emit.DialectCapabilities for Emitter. Returns
// (req, true) when the cap is in pgCatalog, (_, false) when unknown.
// Unknown cap = compiler bug (emitter referenced a cap the catalog
// doesn't list); callers surface via diagnostic.
func (Emitter) Requirement(cap string) (emit.Requirement, bool) {
	r, ok := pgCatalog[cap]
	return r, ok
}

// Compile-time guarantee Emitter satisfies the DialectCapabilities
// contract. SQL dialects MUST satisfy this interface (per emit/
// capabilities.go); KV / non-SQL dialects (redis) may opt out and
// engine.buildManifest handles the absence gracefully.
var _ emit.DialectCapabilities = Emitter{}
