package postgres

import (
	"fmt"
	"strconv"
	"strings"

	irpb "github.com/MrS1lentcz/wandering-compiler/srcgo/pb/domains/compiler/types/ir"
)

// renderColumn produces one indented line of the CREATE TABLE body. Layout:
//
//	<name>  <TYPE>[ NULL|NOT NULL][ DEFAULT <expr>][ GENERATED BY DEFAULT AS IDENTITY][ PRIMARY KEY][ REFERENCES tgt(col) ON DELETE <act>]
//
// Inline PRIMARY KEY is only used when the table has a single PK column.
// The emitter falls back to a table-level PRIMARY KEY line for composite
// keys (see emit.go).
func renderColumn(t *irpb.Table, col *irpb.Column, colByProto map[string]*irpb.Column) (string, error) {
	typeSQL, err := columnType(t.GetName(), col)
	if err != nil {
		return "", fmt.Errorf("column %q: %w", col.GetProtoName(), err)
	}

	parts := []string{col.GetName(), typeSQL}

	// Nullability.
	if col.GetNullable() {
		parts = append(parts, "NULL")
	} else {
		parts = append(parts, "NOT NULL")
	}

	// IDENTITY is a column modifier, not a DEFAULT — they are mutually
	// exclusive in IR (ir.Build enforces IDENTITY requires integer + ID + pk).
	// D18 — GeneratedExpr is the third mutually-exclusive value-source: a
	// STORED generated column computes itself on every row and rejects
	// DEFAULT / IDENTITY at apply time; ir.Build has already rejected the
	// combination, so the chain is safe as an else-if.
	if isIdentity(col) {
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	} else if def := col.GetDefault(); def != nil {
		expr, defErr := defaultExpr(col, def)
		if defErr != nil {
			return "", fmt.Errorf("column %q: %w", col.GetProtoName(), defErr)
		}
		parts = append(parts, "DEFAULT "+expr)
	} else if expr := col.GetGeneratedExpr(); expr != "" {
		parts = append(parts, fmt.Sprintf("GENERATED ALWAYS AS (%s) STORED", expr))
	}

	// Inline single-column PK. Composite keys are emitted as a separate
	// PRIMARY KEY (…) line by the caller.
	if col.GetPk() && len(t.GetPrimaryKey()) == 1 {
		parts = append(parts, "PRIMARY KEY")
	}

	// Inline FK reference. An ir.Column may be the owning side of at most one
	// FK in iter-1; we scan the table's FK list for a match.
	for _, fk := range t.GetForeignKeys() {
		if fk.GetColumn() != col.GetProtoName() {
			continue
		}
		tgtTable := fk.GetTargetTable()
		tgtCol := fk.GetTargetColumn()
		// The target may live in the same table (self-FK) or another table in
		// the same schema. resolveFKs already verified existence; we trust
		// the IR here.
		action := fkActionSQL(fk.GetOnDelete())
		parts = append(parts, fmt.Sprintf("REFERENCES %s(%s)", tgtTable, tgtCol))
		if action != "" {
			parts = append(parts, "ON DELETE "+action)
		}
		break
	}

	return "    " + strings.Join(parts, " "), nil
}

// columnType returns the PG column type string for a column.
// Three override paths can short-circuit the carrier × sem-type table:
//
//  1. (w17.pg.field).custom_type — opaque PG-specific escape hatch.
//  2. (w17.db.column).db_type    — enumerated cross-dialect override (D14).
//  3. field.Type preset          — the default data-semantic dispatch.
//
// ir.Build rejects overrides (1) and (2) set simultaneously, so the
// order below is safe: custom_type first, then db_type, then preset.
//
// tableName is used for deriving PG ENUM type names (<table>_<col>) for
// string-carrier SEM_ENUM columns. Callers that synthesise a column
// without a table (pgArrayOf element dispatch) may pass "" — element-
// level SEM_ENUM on LIST/MAP is rejected at IR time.
func columnType(tableName string, col *irpb.Column) (string, error) {
	if pg := col.GetPg(); pg != nil {
		if raw := pg.GetCustomType(); raw != "" {
			return raw, nil
		}
	}
	if col.GetDbType() != irpb.DbType_DB_TYPE_UNSPECIFIED {
		return pgColumnFromDbType(col)
	}

	switch col.GetCarrier() {
	case irpb.Carrier_CARRIER_BOOL:
		return "BOOLEAN", nil

	case irpb.Carrier_CARRIER_BYTES:
		// bytes-carrying-JSON stays bytes on the wire but stored as JSONB.
		if col.GetType() == irpb.SemType_SEM_JSON {
			return "JSONB", nil
		}
		return "BYTEA", nil

	case irpb.Carrier_CARRIER_STRING:
		switch col.GetType() {
		case irpb.SemType_SEM_CHAR, irpb.SemType_SEM_SLUG,
			irpb.SemType_SEM_EMAIL, irpb.SemType_SEM_URL:
			// All four render as VARCHAR(N). CHAR / SLUG require max_len
			// from the author; EMAIL / URL have preset defaults applied
			// at ir.Build.
			if col.GetMaxLen() <= 0 {
				return "", fmt.Errorf("%s requires max_len (ir invariant)", displaySemType(col.GetType()))
			}
			return fmt.Sprintf("VARCHAR(%d)", col.GetMaxLen()), nil
		case irpb.SemType_SEM_TEXT:
			return "TEXT", nil
		case irpb.SemType_SEM_UUID:
			return "UUID", nil
		case irpb.SemType_SEM_JSON:
			return "JSONB", nil
		case irpb.SemType_SEM_IP:
			return "INET", nil
		case irpb.SemType_SEM_TSEARCH:
			return "TSVECTOR", nil
		case irpb.SemType_SEM_ENUM:
			if tableName == "" {
				return "", fmt.Errorf("string+SEM_ENUM requires table context for CREATE TYPE name derivation")
			}
			return pgEnumTypeName(tableName, col.GetName()), nil
		case irpb.SemType_SEM_DECIMAL:
			if col.GetPrecision() <= 0 {
				return "", fmt.Errorf("DECIMAL requires precision (ir invariant)")
			}
			if col.Scale != nil {
				return fmt.Sprintf("NUMERIC(%d, %d)", col.GetPrecision(), *col.Scale), nil
			}
			return fmt.Sprintf("NUMERIC(%d)", col.GetPrecision()), nil
		}

	case irpb.Carrier_CARRIER_INT32:
		switch col.GetType() {
		case irpb.SemType_SEM_NUMBER, irpb.SemType_SEM_ID, irpb.SemType_SEM_ENUM:
			// int32 + SEM_ENUM: storage stays INTEGER; membership is enforced
			// by the CHECK IN (numbers) the IR attaches in resolveEnumColumn.
			return "INTEGER", nil
		case irpb.SemType_SEM_COUNTER:
			// COUNTER is defined as int64 in D2; int32 is not valid here but
			// the IR builder already rejects the combination. Keep the branch
			// defensive so a future edit doesn't silently produce INTEGER.
			return "", fmt.Errorf("COUNTER requires int64 carrier (ir invariant)")
		}

	case irpb.Carrier_CARRIER_INT64:
		switch col.GetType() {
		case irpb.SemType_SEM_NUMBER, irpb.SemType_SEM_ID, irpb.SemType_SEM_COUNTER, irpb.SemType_SEM_ENUM:
			// int64 + SEM_ENUM: storage stays BIGINT; CHECK IN (numbers)
			// enforces membership (see resolveEnumColumn).
			return "BIGINT", nil
		}

	case irpb.Carrier_CARRIER_DOUBLE:
		switch col.GetType() {
		case irpb.SemType_SEM_NUMBER:
			return "DOUBLE PRECISION", nil
		case irpb.SemType_SEM_MONEY:
			return "NUMERIC(19, 4)", nil
		case irpb.SemType_SEM_PERCENTAGE:
			return "NUMERIC(5, 2)", nil
		case irpb.SemType_SEM_RATIO:
			return "NUMERIC(5, 4)", nil
		}

	case irpb.Carrier_CARRIER_TIMESTAMP:
		switch col.GetType() {
		case irpb.SemType_SEM_DATE:
			return "DATE", nil
		case irpb.SemType_SEM_TIME:
			return "TIME", nil
		case irpb.SemType_SEM_DATETIME:
			return "TIMESTAMPTZ", nil
		}

	case irpb.Carrier_CARRIER_DURATION:
		return "INTERVAL", nil

	case irpb.Carrier_CARRIER_MAP:
		// map<K, V> dispatch:
		//   value is string scalar   → HSTORE (iter-1.6 default, requires hstore extension)
		//   everything else          → JSONB
		if !col.GetElementIsMessage() && col.GetElementCarrier() == irpb.Carrier_CARRIER_STRING {
			return "HSTORE", nil
		}
		return "JSONB", nil

	case irpb.Carrier_CARRIER_LIST:
		// repeated X dispatch:
		//   message element          → JSONB
		//   scalar element, AUTO     → <element_pg_type>[] (element default sem)
		//   scalar element, sem set  → <element_pg_type>[] (element's refined sem)
		if col.GetElementIsMessage() {
			return "JSONB", nil
		}
		return pgArrayOf(col)
	}

	return "", fmt.Errorf("no PG type mapping for carrier=%s type=%s (ir invariant violated)",
		displayCarrier(col.GetCarrier()), displaySemType(col.GetType()))
}

// pgArrayOf renders a native PG array of the column's element carrier.
// The element's sem-type refinement lives on col.Type (list convention —
// on list carrier col.Type is the element's sem). AUTO falls back to
// the element carrier's default sem.
func pgArrayOf(col *irpb.Column) (string, error) {
	// Build a synthetic element Column to reuse columnType's carrier×sem
	// dispatch without duplicating the table.
	elementSem := col.GetType()
	if elementSem == irpb.SemType_SEM_AUTO {
		elementSem = elementDefaultSemFor(col.GetElementCarrier())
	}
	element := &irpb.Column{
		Carrier:   col.GetElementCarrier(),
		Type:      elementSem,
		MaxLen:    col.GetMaxLen(),
		Precision: col.GetPrecision(),
		Scale:     col.Scale,
	}
	// Element has no table context — SEM_ENUM on list/map elements is
	// rejected at IR time (resolveEnumColumn's scalar-only guard), so
	// passing "" never reaches the ENUM branch.
	elemType, err := columnType("", element)
	if err != nil {
		return "", fmt.Errorf("pgArrayOf: element: %w", err)
	}
	return elemType + "[]", nil
}

// elementDefaultSemFor mirrors ir.defaultSemTypeFor for element-level
// dispatch on list carriers. Kept in the emitter to avoid reaching into
// ir internals.
func elementDefaultSemFor(carrier irpb.Carrier) irpb.SemType {
	switch carrier {
	case irpb.Carrier_CARRIER_STRING:
		return irpb.SemType_SEM_TEXT
	case irpb.Carrier_CARRIER_INT32, irpb.Carrier_CARRIER_INT64, irpb.Carrier_CARRIER_DOUBLE:
		return irpb.SemType_SEM_NUMBER
	case irpb.Carrier_CARRIER_TIMESTAMP:
		return irpb.SemType_SEM_DATETIME
	case irpb.Carrier_CARRIER_DURATION:
		return irpb.SemType_SEM_INTERVAL
	}
	return irpb.SemType_SEM_UNSPECIFIED
}

// defaultExpr renders an ir.Default to a PG DEFAULT expression (without the
// leading "DEFAULT " keyword).
func defaultExpr(col *irpb.Column, def *irpb.Default) (string, error) {
	switch v := def.GetVariant().(type) {
	case *irpb.Default_LiteralString:
		return sqlStringLiteral(v.LiteralString), nil
	case *irpb.Default_LiteralInt:
		return strconv.FormatInt(v.LiteralInt, 10), nil
	case *irpb.Default_LiteralDouble:
		return fmtDouble(v.LiteralDouble), nil
	case *irpb.Default_Auto:
		return autoExpr(col, v.Auto)
	default:
		return "", fmt.Errorf("unknown Default variant %T", def.GetVariant())
	}
}

// autoExpr resolves AutoKind to a PG expression. NOW is sem-type-sensitive
// because DATE / TIME / DATETIME render differently.
func autoExpr(col *irpb.Column, kind irpb.AutoKind) (string, error) {
	switch kind {
	case irpb.AutoKind_AUTO_NOW:
		switch col.GetType() {
		case irpb.SemType_SEM_DATE:
			return "CURRENT_DATE", nil
		case irpb.SemType_SEM_TIME:
			return "CURRENT_TIME", nil
		case irpb.SemType_SEM_DATETIME:
			return "NOW()", nil
		}
		return "", fmt.Errorf("AUTO_NOW on unsupported sem type %s", displaySemType(col.GetType()))
	case irpb.AutoKind_AUTO_UUID_V4:
		return "gen_random_uuid()", nil
	case irpb.AutoKind_AUTO_UUID_V7:
		// PG 18+ has uuidv7() built in (RFC 9562). On PG 14–17 the target
		// needs a compatible extension loaded (e.g. `pg_uuidv7`) or apply
		// fails with `function uuidv7() does not exist`. The compiler
		// never gates on extension availability — it emits the call and
		// surfaces extension requirements in docs (iteration-1.md
		// "Apply requirements") and via `(w17.pg.field).required_extensions`
		// for the hosted platform to act on.
		return "uuidv7()", nil
	case irpb.AutoKind_AUTO_EMPTY_JSON_ARRAY:
		return "'[]'", nil
	case irpb.AutoKind_AUTO_EMPTY_JSON_OBJECT:
		return "'{}'", nil
	case irpb.AutoKind_AUTO_TRUE:
		return "TRUE", nil
	case irpb.AutoKind_AUTO_FALSE:
		return "FALSE", nil
	case irpb.AutoKind_AUTO_IDENTITY:
		// Handled by isIdentity in renderColumn; reaching here means the
		// caller mis-dispatched.
		return "", fmt.Errorf("AUTO_IDENTITY is a column modifier, not a DEFAULT expression")
	}
	return "", fmt.Errorf("unknown AutoKind %s", kind)
}

// pgColumnFromDbType maps an explicit (w17.db.column).db_type to its PG
// column type. VARCHAR reads max_len from the column; NUMERIC reads
// precision + scale. BLOB folds into BYTEA (PG has no BLOB type). Every
// other value is a direct-name mapping.
func pgColumnFromDbType(col *irpb.Column) (string, error) {
	switch col.GetDbType() {
	case irpb.DbType_DBT_TEXT:
		return "TEXT", nil
	case irpb.DbType_DBT_VARCHAR:
		if col.GetMaxLen() <= 0 {
			return "", fmt.Errorf("db_type: VARCHAR requires max_len (ir invariant)")
		}
		return fmt.Sprintf("VARCHAR(%d)", col.GetMaxLen()), nil
	case irpb.DbType_DBT_CITEXT:
		return "CITEXT", nil
	case irpb.DbType_DBT_JSON:
		return "JSON", nil
	case irpb.DbType_DBT_JSONB:
		return "JSONB", nil
	case irpb.DbType_DBT_HSTORE:
		return "HSTORE", nil
	case irpb.DbType_DBT_INET:
		return "INET", nil
	case irpb.DbType_DBT_CIDR:
		return "CIDR", nil
	case irpb.DbType_DBT_MACADDR:
		return "MACADDR", nil
	case irpb.DbType_DBT_TSVECTOR:
		return "TSVECTOR", nil
	case irpb.DbType_DBT_UUID:
		return "UUID", nil
	case irpb.DbType_DBT_SMALLINT:
		return "SMALLINT", nil
	case irpb.DbType_DBT_INTEGER:
		return "INTEGER", nil
	case irpb.DbType_DBT_BIGINT:
		return "BIGINT", nil
	case irpb.DbType_DBT_REAL:
		return "REAL", nil
	case irpb.DbType_DBT_DOUBLE_PRECISION:
		return "DOUBLE PRECISION", nil
	case irpb.DbType_DBT_NUMERIC:
		if col.GetPrecision() <= 0 {
			return "", fmt.Errorf("db_type: NUMERIC requires precision (ir invariant)")
		}
		if col.Scale != nil {
			return fmt.Sprintf("NUMERIC(%d, %d)", col.GetPrecision(), *col.Scale), nil
		}
		return fmt.Sprintf("NUMERIC(%d)", col.GetPrecision()), nil
	case irpb.DbType_DBT_DATE:
		return "DATE", nil
	case irpb.DbType_DBT_TIME:
		return "TIME", nil
	case irpb.DbType_DBT_TIMESTAMP:
		return "TIMESTAMP", nil
	case irpb.DbType_DBT_TIMESTAMPTZ:
		return "TIMESTAMPTZ", nil
	case irpb.DbType_DBT_INTERVAL:
		return "INTERVAL", nil
	case irpb.DbType_DBT_BYTEA, irpb.DbType_DBT_BLOB:
		return "BYTEA", nil
	case irpb.DbType_DBT_BOOLEAN:
		return "BOOLEAN", nil
	}
	return "", fmt.Errorf("postgres: unknown db_type %s (ir invariant)", col.GetDbType())
}

func isIdentity(col *irpb.Column) bool {
	def := col.GetDefault()
	if def == nil {
		return false
	}
	auto, ok := def.GetVariant().(*irpb.Default_Auto)
	return ok && auto.Auto == irpb.AutoKind_AUTO_IDENTITY
}

func fkActionSQL(a irpb.FKAction) string {
	switch a {
	case irpb.FKAction_FK_ACTION_CASCADE:
		return "CASCADE"
	case irpb.FKAction_FK_ACTION_SET_NULL:
		return "SET NULL"
	case irpb.FKAction_FK_ACTION_RESTRICT:
		return "RESTRICT"
	case irpb.FKAction_FK_ACTION_SET_DEFAULT:
		return "SET DEFAULT"
	}
	return ""
}

// sqlStringLiteral escapes a Go string into a single-quoted PG literal.
// Single quotes are escaped by doubling. Anything that needs E'\…' escapes
// (C-style) can use (w17.pg.field).custom_type on a per-column basis — we
// don't synthesise those here.
func sqlStringLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// displayCarrier / displaySemType are the package-local equivalents of the
// ir/display.go helpers. Duplicated rather than exported from ir/ because
// they are diagnostic-only and the ir/ helpers live on unexported functions.
func displayCarrier(c irpb.Carrier) string {
	return strings.TrimPrefix(c.String(), "CARRIER_")
}

func displaySemType(s irpb.SemType) string {
	return strings.TrimPrefix(s.String(), "SEM_")
}

// pgEnumTypeName derives the PG ENUM type name for a string-carrier
// SEM_ENUM column. Single source of truth shared between columnType
// (renders the column type), emitAddTable (prepends CREATE TYPE and
// appends DROP TYPE), and the IR-time identifier validation in
// buildTable. The <table>_<column> shape matches the constraint-name
// convention and is NAMEDATALEN-validated at IR time.
func pgEnumTypeName(tableName, colName string) string {
	return tableName + "_" + colName
}
