package postgres

import (
	"fmt"
	"strconv"
	"strings"

	irpb "github.com/MrS1lentcz/wandering-compiler/srcgo/pb/domains/compiler/types/ir"
)

// renderColumn produces one indented line of the CREATE TABLE body. Layout:
//
//	<name>  <TYPE>[ NULL|NOT NULL][ DEFAULT <expr>][ GENERATED BY DEFAULT AS IDENTITY][ PRIMARY KEY][ REFERENCES tgt(col) ON DELETE <act>]
//
// Inline PRIMARY KEY is only used when the table has a single PK column.
// The emitter falls back to a table-level PRIMARY KEY line for composite
// keys (see emit.go).
func renderColumn(t *irpb.Table, col *irpb.Column, colByProto map[string]*irpb.Column) (string, error) {
	typeSQL, err := columnType(col)
	if err != nil {
		return "", fmt.Errorf("column %q: %w", col.GetProtoName(), err)
	}

	parts := []string{col.GetName(), typeSQL}

	// Nullability.
	if col.GetNullable() {
		parts = append(parts, "NULL")
	} else {
		parts = append(parts, "NOT NULL")
	}

	// IDENTITY is a column modifier, not a DEFAULT — they are mutually
	// exclusive in IR (ir.Build enforces IDENTITY requires integer + ID + pk).
	if isIdentity(col) {
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	} else if def := col.GetDefault(); def != nil {
		expr, defErr := defaultExpr(col, def)
		if defErr != nil {
			return "", fmt.Errorf("column %q: %w", col.GetProtoName(), defErr)
		}
		parts = append(parts, "DEFAULT "+expr)
	}

	// Inline single-column PK. Composite keys are emitted as a separate
	// PRIMARY KEY (…) line by the caller.
	if col.GetPk() && len(t.GetPrimaryKey()) == 1 {
		parts = append(parts, "PRIMARY KEY")
	}

	// Inline FK reference. An ir.Column may be the owning side of at most one
	// FK in iter-1; we scan the table's FK list for a match.
	for _, fk := range t.GetForeignKeys() {
		if fk.GetColumn() != col.GetProtoName() {
			continue
		}
		tgtTable := fk.GetTargetTable()
		tgtCol := fk.GetTargetColumn()
		// The target may live in the same table (self-FK) or another table in
		// the same schema. resolveFKs already verified existence; we trust
		// the IR here.
		action := fkActionSQL(fk.GetOnDelete())
		parts = append(parts, fmt.Sprintf("REFERENCES %s(%s)", tgtTable, tgtCol))
		if action != "" {
			parts = append(parts, "ON DELETE "+action)
		}
		break
	}

	return "    " + strings.Join(parts, " "), nil
}

// columnType returns the PG column type string for a column. PG passthrough
// (custom_type, jsonb/inet/tsvector/hstore) short-circuits the semantic
// dispatch.
func columnType(col *irpb.Column) (string, error) {
	if pg := col.GetPg(); pg != nil {
		if raw := pg.GetCustomType(); raw != "" {
			return raw, nil
		}
		switch {
		case pg.GetJsonb():
			return "JSONB", nil
		case pg.GetInet():
			return "INET", nil
		case pg.GetTsvector():
			return "TSVECTOR", nil
		case pg.GetHstore():
			return "HSTORE", nil
		}
	}

	switch col.GetCarrier() {
	case irpb.Carrier_CARRIER_BOOL:
		return "BOOLEAN", nil

	case irpb.Carrier_CARRIER_BYTES:
		return "BYTEA", nil

	case irpb.Carrier_CARRIER_STRING:
		switch col.GetType() {
		case irpb.SemType_SEM_CHAR, irpb.SemType_SEM_SLUG:
			if col.GetMaxLen() <= 0 {
				return "", fmt.Errorf("%s requires max_len (ir invariant)", displaySemType(col.GetType()))
			}
			return fmt.Sprintf("VARCHAR(%d)", col.GetMaxLen()), nil
		case irpb.SemType_SEM_TEXT, irpb.SemType_SEM_URL:
			return "TEXT", nil
		case irpb.SemType_SEM_UUID:
			return "UUID", nil
		case irpb.SemType_SEM_EMAIL:
			return "VARCHAR(320)", nil
		case irpb.SemType_SEM_DECIMAL:
			if col.GetPrecision() <= 0 {
				return "", fmt.Errorf("DECIMAL requires precision (ir invariant)")
			}
			if col.Scale != nil {
				return fmt.Sprintf("NUMERIC(%d, %d)", col.GetPrecision(), *col.Scale), nil
			}
			return fmt.Sprintf("NUMERIC(%d)", col.GetPrecision()), nil
		}

	case irpb.Carrier_CARRIER_INT32:
		switch col.GetType() {
		case irpb.SemType_SEM_NUMBER, irpb.SemType_SEM_ID:
			return "INTEGER", nil
		case irpb.SemType_SEM_COUNTER:
			// COUNTER is defined as int64 in D2; int32 is not valid here but
			// the IR builder already rejects the combination. Keep the branch
			// defensive so a future edit doesn't silently produce INTEGER.
			return "", fmt.Errorf("COUNTER requires int64 carrier (ir invariant)")
		}

	case irpb.Carrier_CARRIER_INT64:
		switch col.GetType() {
		case irpb.SemType_SEM_NUMBER, irpb.SemType_SEM_ID, irpb.SemType_SEM_COUNTER:
			return "BIGINT", nil
		}

	case irpb.Carrier_CARRIER_DOUBLE:
		switch col.GetType() {
		case irpb.SemType_SEM_NUMBER:
			return "DOUBLE PRECISION", nil
		case irpb.SemType_SEM_MONEY:
			return "NUMERIC(19, 4)", nil
		case irpb.SemType_SEM_PERCENTAGE:
			return "NUMERIC(5, 2)", nil
		case irpb.SemType_SEM_RATIO:
			return "NUMERIC(5, 4)", nil
		}

	case irpb.Carrier_CARRIER_TIMESTAMP:
		switch col.GetType() {
		case irpb.SemType_SEM_DATE:
			return "DATE", nil
		case irpb.SemType_SEM_TIME:
			return "TIME", nil
		case irpb.SemType_SEM_DATETIME:
			return "TIMESTAMPTZ", nil
		}

	case irpb.Carrier_CARRIER_DURATION:
		return "INTERVAL", nil
	}

	return "", fmt.Errorf("no PG type mapping for carrier=%s type=%s (ir invariant violated)",
		displayCarrier(col.GetCarrier()), displaySemType(col.GetType()))
}

// defaultExpr renders an ir.Default to a PG DEFAULT expression (without the
// leading "DEFAULT " keyword).
func defaultExpr(col *irpb.Column, def *irpb.Default) (string, error) {
	switch v := def.GetVariant().(type) {
	case *irpb.Default_LiteralString:
		return sqlStringLiteral(v.LiteralString), nil
	case *irpb.Default_LiteralInt:
		return strconv.FormatInt(v.LiteralInt, 10), nil
	case *irpb.Default_LiteralDouble:
		return fmtDouble(v.LiteralDouble), nil
	case *irpb.Default_Auto:
		return autoExpr(col, v.Auto)
	default:
		return "", fmt.Errorf("unknown Default variant %T", def.GetVariant())
	}
}

// autoExpr resolves AutoKind to a PG expression. NOW is sem-type-sensitive
// because DATE / TIME / DATETIME render differently.
func autoExpr(col *irpb.Column, kind irpb.AutoKind) (string, error) {
	switch kind {
	case irpb.AutoKind_AUTO_NOW:
		switch col.GetType() {
		case irpb.SemType_SEM_DATE:
			return "CURRENT_DATE", nil
		case irpb.SemType_SEM_TIME:
			return "CURRENT_TIME", nil
		case irpb.SemType_SEM_DATETIME:
			return "NOW()", nil
		}
		return "", fmt.Errorf("AUTO_NOW on unsupported sem type %s", displaySemType(col.GetType()))
	case irpb.AutoKind_AUTO_UUID_V4:
		return "gen_random_uuid()", nil
	case irpb.AutoKind_AUTO_UUID_V7:
		// PG 18+ has uuidv7() built in (RFC 9562). On PG 14–17 the target
		// needs a compatible extension loaded (e.g. `pg_uuidv7`) or apply
		// fails with `function uuidv7() does not exist`. The compiler
		// never gates on extension availability — it emits the call and
		// surfaces extension requirements in docs (iteration-1.md
		// "Apply requirements") and via `(w17.pg.field).required_extensions`
		// for the hosted platform to act on.
		return "uuidv7()", nil
	case irpb.AutoKind_AUTO_EMPTY_JSON_ARRAY:
		return "'[]'", nil
	case irpb.AutoKind_AUTO_EMPTY_JSON_OBJECT:
		return "'{}'", nil
	case irpb.AutoKind_AUTO_TRUE:
		return "TRUE", nil
	case irpb.AutoKind_AUTO_FALSE:
		return "FALSE", nil
	case irpb.AutoKind_AUTO_IDENTITY:
		// Handled by isIdentity in renderColumn; reaching here means the
		// caller mis-dispatched.
		return "", fmt.Errorf("AUTO_IDENTITY is a column modifier, not a DEFAULT expression")
	}
	return "", fmt.Errorf("unknown AutoKind %s", kind)
}

func isIdentity(col *irpb.Column) bool {
	def := col.GetDefault()
	if def == nil {
		return false
	}
	auto, ok := def.GetVariant().(*irpb.Default_Auto)
	return ok && auto.Auto == irpb.AutoKind_AUTO_IDENTITY
}

func fkActionSQL(a irpb.FKAction) string {
	switch a {
	case irpb.FKAction_FK_ACTION_CASCADE:
		return "CASCADE"
	case irpb.FKAction_FK_ACTION_SET_NULL:
		return "SET NULL"
	case irpb.FKAction_FK_ACTION_RESTRICT:
		return "RESTRICT"
	case irpb.FKAction_FK_ACTION_SET_DEFAULT:
		return "SET DEFAULT"
	}
	return ""
}

// sqlStringLiteral escapes a Go string into a single-quoted PG literal.
// Single quotes are escaped by doubling. Anything that needs E'\…' escapes
// (C-style) can use (w17.pg.field).custom_type on a per-column basis — we
// don't synthesise those here.
func sqlStringLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// displayCarrier / displaySemType are the package-local equivalents of the
// ir/display.go helpers. Duplicated rather than exported from ir/ because
// they are diagnostic-only and the ir/ helpers live on unexported functions.
func displayCarrier(c irpb.Carrier) string {
	return strings.TrimPrefix(c.String(), "CARRIER_")
}

func displaySemType(s irpb.SemType) string {
	return strings.TrimPrefix(s.String(), "SEM_")
}
