package postgres_test

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/emit"
	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/emit/postgres"
	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/ir"
	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/loader"
	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/plan"
	irpb "github.com/MrS1lentcz/wandering-compiler/srcgo/pb/domains/compiler/types/ir"
	planpb "github.com/MrS1lentcz/wandering-compiler/srcgo/pb/domains/compiler/types/plan"
)

const protoImportPath = "../../../../../proto"

// Pipeline smoke: run the ir happy fixture all the way through Build ->
// Diff -> Emit. Asserts structural facts in the SQL rather than exact
// string equality — the golden-file test suite is M8.
func TestEmitAddTableFromHappyFixture(t *testing.T) {
	up, down := runPipeline(t, "../../ir/testdata/happy.proto")

	// customers table must come first (alphabetical ordering from Diff).
	iCustomers := strings.Index(up, "CREATE TABLE customers")
	iOrders := strings.Index(up, "CREATE TABLE orders")
	if iCustomers < 0 || iOrders < 0 || iCustomers >= iOrders {
		t.Fatalf("ordering broken:\ncustomers@%d orders@%d\n\n%s", iCustomers, iOrders, up)
	}

	mustContain(t, up, "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	mustContain(t, up, "name VARCHAR(120) NOT NULL")
	// EMAIL accepts max_len as an override (D13): max_len: 255 → VARCHAR(255).
	// No separate Length CHECK — VARCHAR(N) subsumes the upper bound.
	mustContain(t, up, "email VARCHAR(255) NOT NULL")
	mustContain(t, up, "CONSTRAINT customers_email_format CHECK (email ~ ")
	mustContain(t, up, "CONSTRAINT customers_name_blank CHECK (name <> '')")

	mustContain(t, up, "customer_id BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL")
	mustContain(t, up, "status VARCHAR(16) NOT NULL")
	mustContain(t, up, "CONSTRAINT orders_status_choices CHECK (status IN ('PENDING', 'PAID'))")
	mustContain(t, up, "total NUMERIC(19, 4) NOT NULL")
	mustContain(t, up, "created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")
	mustContain(t, up, "metadata JSONB")

	// PK columns must not get a redundant unique index — PRIMARY KEY already
	// implies one.
	if strings.Contains(up, "CREATE UNIQUE INDEX customers_id_uidx") {
		t.Errorf("redundant UNIQUE INDEX on PK column 'id' of customers:\n%s", up)
	}

	// Table-level index from (w17.db.table).indexes.
	mustContain(t, up, "CREATE INDEX orders_customer_id_status_idx ON orders (customer_id, status);")
	// Synthetic single-col plain index from (w17.db.column).index.
	mustContain(t, up, "CREATE INDEX orders_customer_id_idx ON orders (customer_id);")
	// Synthetic UNIQUE INDEX from (w17.field).unique on email.
	mustContain(t, up, "CREATE UNIQUE INDEX customers_email_uidx ON customers (email);")

	// Down: indexes dropped before table, tables dropped in reverse creation.
	iDropOrdersTbl := strings.Index(down, "DROP TABLE IF EXISTS orders;")
	iDropCustTbl := strings.Index(down, "DROP TABLE IF EXISTS customers;")
	iDropOrdersIdx := strings.Index(down, "DROP INDEX IF EXISTS orders_customer_id_status_idx;")
	if iDropOrdersIdx < 0 || iDropOrdersTbl < 0 || iDropCustTbl < 0 {
		t.Fatalf("down missing expected drops:\n%s", down)
	}
	if !(iDropOrdersIdx < iDropOrdersTbl && iDropOrdersTbl < iDropCustTbl) {
		t.Fatalf("down order wrong (indexes < orders < customers expected):\n%s", down)
	}
}

// MONEY renders as NUMERIC(19, 4). The happy fixture's `total` is MONEY —
// above test had a sloppy expectation; keep this focused check separate so
// a MONEY rendering regression is obvious.
func TestMoneyRendersNumeric(t *testing.T) {
	col := &irpb.Column{
		Name:      "total",
		ProtoName: "total",
		Carrier:   irpb.Carrier_CARRIER_DOUBLE,
		Type:      irpb.SemType_SEM_MONEY,
	}
	table := &irpb.Table{Name: "t", Columns: []*irpb.Column{col}}
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	up, _, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if !strings.Contains(up, "total NUMERIC(19, 4)") {
		t.Errorf("MONEY not rendered as NUMERIC(19, 4):\n%s", up)
	}
}

// Determinism: two independent pipeline runs produce byte-identical up/down.
// This is AC #4. Any map iteration or random ordering in the emit path
// surfaces here.
func TestEmitDeterministic(t *testing.T) {
	up1, down1 := runPipeline(t, "../../ir/testdata/happy.proto")
	up2, down2 := runPipeline(t, "../../ir/testdata/happy.proto")
	if up1 != up2 {
		t.Errorf("up differs across runs")
	}
	if down1 != down2 {
		t.Errorf("down differs across runs")
	}
}

// Single-col PK is inlined on the column line; composite PK is a table-level
// PRIMARY KEY (…) entry. No composite-PK test fixture yet — exercise the
// composite path with a hand-built IR so we catch a regression before a real
// schema surfaces it.
func TestCompositePKRendersTableLevel(t *testing.T) {
	table := &irpb.Table{
		Name: "memberships",
		Columns: []*irpb.Column{
			{Name: "user_id", ProtoName: "user_id", Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID, Pk: true},
			{Name: "group_id", ProtoName: "group_id", Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID, Pk: true},
		},
		PrimaryKey: []string{"user_id", "group_id"},
	}
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	up, _, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if strings.Contains(up, "user_id BIGINT NOT NULL PRIMARY KEY") {
		t.Errorf("composite PK incorrectly inlined on user_id:\n%s", up)
	}
	if !strings.Contains(up, "PRIMARY KEY (user_id, group_id)") {
		t.Errorf("composite PK not rendered as table-level:\n%s", up)
	}
}

// Unknown op variant returns a clear error (M5 stub exercises the same
// contract — this keeps the postgres impl honest).
func TestUnknownOpVariantErrors(t *testing.T) {
	_, _, err := postgres.Emitter{}.EmitOp(&planpb.Op{})
	if err == nil {
		t.Fatal("empty Op succeeded; want error on unsupported variant")
	}
}

// ---- helpers ----

func runPipeline(t *testing.T, protoPath string) (up, down string) {
	t.Helper()
	base, file := filepath.Split(protoPath)
	lf, err := loader.Load(context.Background(), file, []string{base, protoImportPath})
	if err != nil {
		t.Fatalf("loader.Load: %v", err)
	}
	schema, err := ir.Build(lf)
	if err != nil {
		t.Fatalf("ir.Build: %v", err)
	}
	p, err := plan.Diff(nil, schema)
	if err != nil {
		t.Fatalf("plan.Diff: %v", err)
	}
	up, down, err = emit.Emit(postgres.Emitter{}, p)
	if err != nil {
		t.Fatalf("emit.Emit: %v", err)
	}
	return up, down
}

func mustContain(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("missing: %q\n\nin:\n%s", needle, haystack)
	}
}
