package postgres_test

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/emit"
	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/emit/postgres"
	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/ir"
	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/loader"
	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/plan"
	irpb "github.com/MrS1lentcz/wandering-compiler/srcgo/pb/domains/compiler/types/ir"
	planpb "github.com/MrS1lentcz/wandering-compiler/srcgo/pb/domains/compiler/types/plan"
)

const protoImportPath = "../../../../../proto"

// Pipeline smoke: run the ir happy fixture all the way through Build ->
// Diff -> Emit. Asserts structural facts in the SQL rather than exact
// string equality — the golden-file test suite is M8.
func TestEmitAddTableFromHappyFixture(t *testing.T) {
	up, down := runPipeline(t, "../../ir/testdata/happy.proto")

	// customers table must come first (alphabetical ordering from Diff).
	iCustomers := strings.Index(up, "CREATE TABLE customers")
	iOrders := strings.Index(up, "CREATE TABLE orders")
	if iCustomers < 0 || iOrders < 0 || iCustomers >= iOrders {
		t.Fatalf("ordering broken:\ncustomers@%d orders@%d\n\n%s", iCustomers, iOrders, up)
	}

	mustContain(t, up, "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	mustContain(t, up, "name VARCHAR(120) NOT NULL")
	// EMAIL accepts max_len as an override (D13): max_len: 255 → VARCHAR(255).
	// No separate Length CHECK — VARCHAR(N) subsumes the upper bound.
	mustContain(t, up, "email VARCHAR(255) NOT NULL")
	mustContain(t, up, "CONSTRAINT customers_email_format CHECK (email ~ ")
	mustContain(t, up, "CONSTRAINT customers_name_blank CHECK (name <> '')")

	mustContain(t, up, "customer_id BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL")
	mustContain(t, up, "status VARCHAR(16) NOT NULL")
	mustContain(t, up, "CONSTRAINT orders_status_choices CHECK (status IN ('PENDING', 'PAID'))")
	mustContain(t, up, "total NUMERIC(19, 4) NOT NULL")
	mustContain(t, up, "created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")
	mustContain(t, up, "metadata JSONB")

	// PK columns must not get a redundant unique index — PRIMARY KEY already
	// implies one.
	if strings.Contains(up, "CREATE UNIQUE INDEX customers_id_uidx") {
		t.Errorf("redundant UNIQUE INDEX on PK column 'id' of customers:\n%s", up)
	}

	// Table-level index from (w17.db.table).indexes.
	mustContain(t, up, "CREATE INDEX orders_customer_id_status_idx ON orders (customer_id, status);")
	// Synthetic single-col plain index from (w17.db.column).index.
	mustContain(t, up, "CREATE INDEX orders_customer_id_idx ON orders (customer_id);")
	// Synthetic UNIQUE INDEX from (w17.field).unique on email.
	mustContain(t, up, "CREATE UNIQUE INDEX customers_email_uidx ON customers (email);")

	// Down: indexes dropped before table, tables dropped in reverse creation.
	iDropOrdersTbl := strings.Index(down, "DROP TABLE IF EXISTS orders;")
	iDropCustTbl := strings.Index(down, "DROP TABLE IF EXISTS customers;")
	iDropOrdersIdx := strings.Index(down, "DROP INDEX IF EXISTS orders_customer_id_status_idx;")
	if iDropOrdersIdx < 0 || iDropOrdersTbl < 0 || iDropCustTbl < 0 {
		t.Fatalf("down missing expected drops:\n%s", down)
	}
	if !(iDropOrdersIdx < iDropOrdersTbl && iDropOrdersTbl < iDropCustTbl) {
		t.Fatalf("down order wrong (indexes < orders < customers expected):\n%s", down)
	}
}

// MONEY renders as NUMERIC(19, 4). The happy fixture's `total` is MONEY —
// above test had a sloppy expectation; keep this focused check separate so
// a MONEY rendering regression is obvious.
func TestMoneyRendersNumeric(t *testing.T) {
	col := &irpb.Column{
		Name:      "total",
		ProtoName: "total",
		Carrier:   irpb.Carrier_CARRIER_DOUBLE,
		Type:      irpb.SemType_SEM_MONEY,
	}
	table := &irpb.Table{Name: "t", Columns: []*irpb.Column{col}}
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	up, _, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if !strings.Contains(up, "total NUMERIC(19, 4)") {
		t.Errorf("MONEY not rendered as NUMERIC(19, 4):\n%s", up)
	}
}

// Determinism: two independent pipeline runs produce byte-identical up/down.
// This is AC #4. Any map iteration or random ordering in the emit path
// surfaces here.
func TestEmitDeterministic(t *testing.T) {
	up1, down1 := runPipeline(t, "../../ir/testdata/happy.proto")
	up2, down2 := runPipeline(t, "../../ir/testdata/happy.proto")
	if up1 != up2 {
		t.Errorf("up differs across runs")
	}
	if down1 != down2 {
		t.Errorf("down differs across runs")
	}
}

// Single-col PK is inlined on the column line; composite PK is a table-level
// PRIMARY KEY (…) entry. No composite-PK test fixture yet — exercise the
// composite path with a hand-built IR so we catch a regression before a real
// schema surfaces it.
func TestCompositePKRendersTableLevel(t *testing.T) {
	table := &irpb.Table{
		Name: "memberships",
		Columns: []*irpb.Column{
			{Name: "user_id", ProtoName: "user_id", Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID, Pk: true},
			{Name: "group_id", ProtoName: "group_id", Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID, Pk: true},
		},
		PrimaryKey: []string{"user_id", "group_id"},
	}
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	up, _, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if strings.Contains(up, "user_id BIGINT NOT NULL PRIMARY KEY") {
		t.Errorf("composite PK incorrectly inlined on user_id:\n%s", up)
	}
	if !strings.Contains(up, "PRIMARY KEY (user_id, group_id)") {
		t.Errorf("composite PK not rendered as table-level:\n%s", up)
	}
}

// Unknown op variant returns a clear error (M5 stub exercises the same
// contract — this keeps the postgres impl honest).
func TestUnknownOpVariantErrors(t *testing.T) {
	_, _, err := postgres.Emitter{}.EmitOp(&planpb.Op{})
	if err == nil {
		t.Fatal("empty Op succeeded; want error on unsupported variant")
	}
}

// TestEmitDropTableMirrorsAddTable — DropTable's up SQL is the
// inverse of AddTable's up: DROP INDEX + DROP TABLE + DROP TYPE.
// Down side rebuilds the table verbatim (= AddTable.up). Tests
// against a hand-built IR with one ENUM column and one secondary
// index so both the table-down and the index/enum cleanup branches
// fire.
func TestEmitDropTableMirrorsAddTable(t *testing.T) {
	table := &irpb.Table{
		Name:       "products",
		MessageFqn: "shop.Product",
		Columns: []*irpb.Column{
			{Name: "id", ProtoName: "id", Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID, Pk: true},
			{Name: "status", ProtoName: "status",
				Carrier:    irpb.Carrier_CARRIER_STRING,
				Type:       irpb.SemType_SEM_ENUM,
				EnumFqn:    "shop.ProductStatus",
				EnumNames:  []string{"DRAFT", "PUBLISHED"},
				EnumNumbers: []int64{1, 2},
			},
		},
		PrimaryKey: []string{"id"},
		Indexes: []*irpb.Index{
			{Fields: []*irpb.IndexField{{Name: "status"}}, Name: "products_status_idx"},
		},
	}

	addOp := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	dropOp := &planpb.Op{Variant: &planpb.Op_DropTable{DropTable: &planpb.DropTable{Table: table}}}

	addUp, _, err := postgres.Emitter{}.EmitOp(addOp)
	if err != nil {
		t.Fatalf("AddTable: %v", err)
	}
	dropUp, dropDown, err := postgres.Emitter{}.EmitOp(dropOp)
	if err != nil {
		t.Fatalf("DropTable: %v", err)
	}

	// up.sql for DropTable must drop the index, the table, and the enum
	// type. Order: index → table → type (table down inversion).
	iIdx := strings.Index(dropUp, "DROP INDEX IF EXISTS products_status_idx;")
	iTbl := strings.Index(dropUp, "DROP TABLE IF EXISTS products;")
	iTyp := strings.Index(dropUp, "DROP TYPE IF EXISTS products_status;")
	if iIdx < 0 || iTbl < 0 || iTyp < 0 {
		t.Fatalf("missing drops in up:\n%s", dropUp)
	}
	if !(iIdx < iTbl && iTbl < iTyp) {
		t.Errorf("drop order wrong (idx<table<type expected):\n%s", dropUp)
	}

	// down.sql for DropTable rebuilds the table — should equal AddTable's up.
	if dropDown != addUp {
		t.Errorf("DropTable.down != AddTable.up:\n--- down ---\n%s\n--- add up ---\n%s", dropDown, addUp)
	}
}

// TestDropTableEmptyNameErrors — defensive: empty table name on the
// op surface bails out with a clear error rather than emitting bogus
// SQL.
func TestDropTableEmptyNameErrors(t *testing.T) {
	op := &planpb.Op{Variant: &planpb.Op_DropTable{DropTable: &planpb.DropTable{Table: &irpb.Table{}}}}
	if _, _, err := (postgres.Emitter{}).EmitOp(op); err == nil {
		t.Fatal("empty table name accepted on DropTable, want error")
	}
}

// TestEmitAddColumnPlain — plain VARCHAR column. Up: ALTER TABLE …
// ADD COLUMN. Down: ALTER TABLE … DROP COLUMN. Schema namespace is
// honoured by the qualifier helper.
func TestEmitAddColumnPlain(t *testing.T) {
	col := &irpb.Column{
		Name: "email", ProtoName: "email", FieldNumber: 2,
		Carrier: irpb.Carrier_CARRIER_STRING, Type: irpb.SemType_SEM_EMAIL, MaxLen: 255,
	}
	op := &planpb.Op{Variant: &planpb.Op_AddColumn{AddColumn: &planpb.AddColumn{
		Ctx: &planpb.TableCtx{
			MessageFqn: "shop.User", TableName: "users",
			NamespaceMode: irpb.NamespaceMode_NAMESPACE_MODE_SCHEMA,
			Namespace:     "auth",
		},
		Column: col,
	}}}
	up, down, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	mustContain(t, up, "ALTER TABLE auth.users ADD COLUMN email VARCHAR(255) NOT NULL")
	mustContain(t, down, "ALTER TABLE auth.users DROP COLUMN email;")
}

// TestEmitAddColumnWithCheck — a column carrying a structured CHECK
// emits the constraint as a separate ALTER TABLE ADD CONSTRAINT after
// the ADD COLUMN statement.
func TestEmitAddColumnWithCheck(t *testing.T) {
	col := &irpb.Column{
		Name: "name", ProtoName: "name", FieldNumber: 2,
		Carrier: irpb.Carrier_CARRIER_STRING, Type: irpb.SemType_SEM_CHAR, MaxLen: 64,
		Checks: []*irpb.Check{
			{Variant: &irpb.Check_Blank{Blank: &irpb.BlankCheck{}}},
		},
	}
	op := &planpb.Op{Variant: &planpb.Op_AddColumn{AddColumn: &planpb.AddColumn{
		Ctx:    &planpb.TableCtx{TableName: "users"},
		Column: col,
	}}}
	up, _, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	mustContain(t, up, "ALTER TABLE users ADD COLUMN name VARCHAR(64) NOT NULL;")
	mustContain(t, up, "ALTER TABLE users ADD CONSTRAINT users_name_blank CHECK (name <> '');")
}

// TestEmitAddColumnEnum — string carrier + SEM_ENUM. ADD COLUMN must be
// preceded by CREATE TYPE; DROP COLUMN followed by DROP TYPE.
func TestEmitAddColumnEnum(t *testing.T) {
	col := &irpb.Column{
		Name: "status", ProtoName: "status", FieldNumber: 3,
		Carrier:     irpb.Carrier_CARRIER_STRING,
		Type:        irpb.SemType_SEM_ENUM,
		EnumFqn:     "shop.PostStatus",
		EnumNames:   []string{"DRAFT", "PUBLISHED"},
		EnumNumbers: []int64{1, 2},
	}
	op := &planpb.Op{Variant: &planpb.Op_AddColumn{AddColumn: &planpb.AddColumn{
		Ctx: &planpb.TableCtx{
			MessageFqn: "shop.Post", TableName: "posts",
		},
		Column: col,
	}}}
	up, down, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	iCT := strings.Index(up, "CREATE TYPE posts_status AS ENUM ('DRAFT', 'PUBLISHED');")
	iAdd := strings.Index(up, "ALTER TABLE posts ADD COLUMN status posts_status NOT NULL;")
	if iCT < 0 || iAdd < 0 || iCT >= iAdd {
		t.Fatalf("ENUM ADD COLUMN order broken (CT@%d ADD@%d):\n%s", iCT, iAdd, up)
	}
	iDrop := strings.Index(down, "ALTER TABLE posts DROP COLUMN status;")
	iDT := strings.Index(down, "DROP TYPE IF EXISTS posts_status;")
	if iDrop < 0 || iDT < 0 || iDrop >= iDT {
		t.Fatalf("ENUM DROP order broken (DROP@%d DT@%d):\n%s", iDrop, iDT, down)
	}
}

// TestEmitRenameTable — symmetric ALTER ... RENAME TO with schema
// qualification on both sides.
func TestEmitRenameTable(t *testing.T) {
	op := &planpb.Op{Variant: &planpb.Op_RenameTable{RenameTable: &planpb.RenameTable{
		Ctx: &planpb.TableCtx{
			TableName: "accounts", MessageFqn: "shop.User",
			NamespaceMode: irpb.NamespaceMode_NAMESPACE_MODE_SCHEMA,
			Namespace:     "auth",
		},
		FromName: "users", ToName: "accounts",
	}}}
	up, down, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if up != "ALTER TABLE auth.users RENAME TO accounts;" {
		t.Errorf("up = %q", up)
	}
	if down != "ALTER TABLE auth.accounts RENAME TO users;" {
		t.Errorf("down = %q", down)
	}
}

// TestEmitSetTableComment — empty `to` drops the comment via IS NULL;
// a non-empty `to` sets via IS '<text>'. Down inverts symmetrically.
func TestEmitSetTableComment(t *testing.T) {
	op := &planpb.Op{Variant: &planpb.Op_SetTableComment{SetTableComment: &planpb.SetTableComment{
		Ctx:  &planpb.TableCtx{TableName: "users"},
		From: "",
		To:   "user accounts",
	}}}
	up, down, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if up != "COMMENT ON TABLE users IS 'user accounts';" {
		t.Errorf("up = %q", up)
	}
	if down != "COMMENT ON TABLE users IS NULL;" {
		t.Errorf("down = %q (want NULL for empty prev)", down)
	}
}

// TestEmitRenameColumn — symmetric ALTER ... RENAME COLUMN. Down
// swaps from/to.
func TestEmitRenameColumn(t *testing.T) {
	op := &planpb.Op{Variant: &planpb.Op_RenameColumn{RenameColumn: &planpb.RenameColumn{
		Ctx: &planpb.TableCtx{
			TableName:     "users",
			NamespaceMode: irpb.NamespaceMode_NAMESPACE_MODE_SCHEMA,
			Namespace:     "auth",
		},
		FieldNumber: 2,
		FromName:    "name",
		ToName:      "display_name",
	}}}
	up, down, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if up != "ALTER TABLE auth.users RENAME COLUMN name TO display_name;" {
		t.Errorf("up = %q, want ALTER TABLE auth.users RENAME COLUMN name TO display_name;", up)
	}
	if down != "ALTER TABLE auth.users RENAME COLUMN display_name TO name;" {
		t.Errorf("down = %q, want reverse rename", down)
	}
}

// TestEmitRenameColumnNoOpRefused — refuse from==to which would emit
// invalid SQL anyway. Defensive against differ malforming the op.
func TestEmitRenameColumnNoOpRefused(t *testing.T) {
	op := &planpb.Op{Variant: &planpb.Op_RenameColumn{RenameColumn: &planpb.RenameColumn{
		Ctx: &planpb.TableCtx{TableName: "users"},
		FromName: "name", ToName: "name",
	}}}
	if _, _, err := (postgres.Emitter{}).EmitOp(op); err == nil {
		t.Fatal("RenameColumn from==to accepted, want error")
	}
}

// TestEmitAddIndexStructured — AddIndex renders the iter-1
// CREATE INDEX shape; down drops by qualified name.
func TestEmitAddIndexStructured(t *testing.T) {
	op := &planpb.Op{Variant: &planpb.Op_AddIndex{AddIndex: &planpb.AddIndex{
		Ctx: &planpb.TableCtx{TableName: "users"},
		Index: &irpb.Index{
			Name: "users_email_idx", Unique: true,
			Fields: []*irpb.IndexField{{Name: "email"}},
		},
		Columns: []*irpb.Column{
			{Name: "email", ProtoName: "email", Carrier: irpb.Carrier_CARRIER_STRING, Type: irpb.SemType_SEM_EMAIL, MaxLen: 255},
		},
	}}}
	up, down, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if up != "CREATE UNIQUE INDEX users_email_idx ON users (email);" {
		t.Errorf("up = %q", up)
	}
	if down != "DROP INDEX IF EXISTS users_email_idx;" {
		t.Errorf("down = %q", down)
	}
}

// TestEmitReplaceIndex — drop+add for both sides. Up: drop from,
// create to. Down: drop to, create from.
func TestEmitReplaceIndex(t *testing.T) {
	op := &planpb.Op{Variant: &planpb.Op_ReplaceIndex{ReplaceIndex: &planpb.ReplaceIndex{
		Ctx: &planpb.TableCtx{TableName: "users"},
		From: &irpb.Index{Name: "users_email_idx", Fields: []*irpb.IndexField{{Name: "email"}}},
		To:   &irpb.Index{Name: "users_email_idx", Fields: []*irpb.IndexField{{Name: "email"}}, Unique: true},
		Columns: []*irpb.Column{
			{Name: "email", ProtoName: "email", Carrier: irpb.Carrier_CARRIER_STRING, Type: irpb.SemType_SEM_EMAIL, MaxLen: 255},
		},
	}}}
	up, down, err := postgres.Emitter{}.EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	mustContain(t, up, "DROP INDEX IF EXISTS users_email_idx;")
	mustContain(t, up, "CREATE UNIQUE INDEX users_email_idx ON users (email);")
	mustContain(t, down, "CREATE INDEX users_email_idx ON users (email);")
}

// TestEmitRawIndexRoundtrip — opaque body passes through verbatim;
// drop is by name, identical regardless of body.
func TestEmitRawIndexRoundtrip(t *testing.T) {
	addOp := &planpb.Op{Variant: &planpb.Op_AddRawIndex{AddRawIndex: &planpb.AddRawIndex{
		Ctx:   &planpb.TableCtx{TableName: "posts"},
		Index: &irpb.RawIndex{Name: "posts_search_gin", Body: "USING gin (search_tsv)"},
	}}}
	up, down, err := postgres.Emitter{}.EmitOp(addOp)
	if err != nil {
		t.Fatalf("AddRawIndex: %v", err)
	}
	if up != "CREATE INDEX posts_search_gin ON posts USING gin (search_tsv);" {
		t.Errorf("up = %q", up)
	}
	if down != "DROP INDEX IF EXISTS posts_search_gin;" {
		t.Errorf("down = %q", down)
	}
}

// TestEmitDropColumnRoundtrip — DropColumn.up = ALTER ... DROP COLUMN;
// DropColumn.down = AddColumn.up for the same column. Confirms the
// emitter's symmetry contract for column-axis ops.
func TestEmitDropColumnRoundtrip(t *testing.T) {
	col := &irpb.Column{
		Name: "legacy", ProtoName: "legacy", FieldNumber: 5,
		Carrier: irpb.Carrier_CARRIER_STRING, Type: irpb.SemType_SEM_TEXT,
	}
	addOp := &planpb.Op{Variant: &planpb.Op_AddColumn{AddColumn: &planpb.AddColumn{
		Ctx:    &planpb.TableCtx{TableName: "users"},
		Column: col,
	}}}
	dropOp := &planpb.Op{Variant: &planpb.Op_DropColumn{DropColumn: &planpb.DropColumn{
		Ctx:    &planpb.TableCtx{TableName: "users"},
		Column: col,
	}}}
	addUp, _, err := postgres.Emitter{}.EmitOp(addOp)
	if err != nil {
		t.Fatalf("AddColumn: %v", err)
	}
	dropUp, dropDown, err := postgres.Emitter{}.EmitOp(dropOp)
	if err != nil {
		t.Fatalf("DropColumn: %v", err)
	}
	mustContain(t, dropUp, "ALTER TABLE users DROP COLUMN legacy;")
	if dropDown != addUp {
		t.Errorf("DropColumn.down != AddColumn.up:\n--- down ---\n%s\n--- add up ---\n%s", dropDown, addUp)
	}
}

// TestAddTableEmptyNameErrors — emitAddTable refuses a table with no
// name. Defensive branch against an ir.Build invariant violation.
func TestAddTableEmptyNameErrors(t *testing.T) {
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: &irpb.Table{}}}}
	if _, _, err := (postgres.Emitter{}).EmitOp(op); err == nil {
		t.Fatal("empty table name accepted, want error")
	}
}

// TestCompositePKUnknownFieldErrors — emitAddTable refuses a PK entry
// that references a column not in Columns. Defensive against a broken
// IR where tbl.PrimaryKey and tbl.Columns disagree.
func TestCompositePKUnknownFieldErrors(t *testing.T) {
	table := &irpb.Table{
		Name:       "t",
		Columns:    []*irpb.Column{{Name: "a", ProtoName: "a", Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID, Pk: true}},
		PrimaryKey: []string{"a", "ghost_column"},
	}
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	_, _, err := (postgres.Emitter{}).EmitOp(op)
	if err == nil {
		t.Fatal("composite PK with unknown field accepted, want error")
	}
	if !strings.Contains(err.Error(), "ghost_column") {
		t.Errorf("error doesn't name the offending field: %v", err)
	}
}

// TestRenderColumnErrorPropagates — renderColumn returns its error
// unwrapped up through writeCreateTable → emitAddTable → EmitOp. Feed
// a synthetic column that's invalid at the emit layer (DECIMAL sem
// without precision; IR normally rejects this, but unit-exercise the
// defensive error path).
func TestRenderColumnErrorPropagates(t *testing.T) {
	table := &irpb.Table{
		Name: "t",
		Columns: []*irpb.Column{{
			Name:      "amount",
			ProtoName: "amount",
			Carrier:   irpb.Carrier_CARRIER_STRING,
			Type:      irpb.SemType_SEM_DECIMAL,
			// no Precision set — columnType errors out
		}},
	}
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	_, _, err := (postgres.Emitter{}).EmitOp(op)
	if err == nil {
		t.Fatal("expected err when column has no precision, got nil")
	}
	if !strings.Contains(err.Error(), "DECIMAL requires precision") {
		t.Errorf("err %q missing DECIMAL precision marker", err.Error())
	}
}

// TestRenderIndexErrorPropagates — renderIndexes error propagates via
// writeIndexStatements. Feed a table whose index references a column
// that resolves to a zero-value (nil in colByProto map).
func TestRenderIndexErrorPropagates(t *testing.T) {
	table := &irpb.Table{
		Name: "t",
		Columns: []*irpb.Column{
			{Name: "id", ProtoName: "id", Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID, Pk: true},
		},
		PrimaryKey: []string{"id"},
		Indexes: []*irpb.Index{
			// Reference a field that doesn't exist — renderIndexField
			// can't resolve the SQL column name.
			{Name: "t_ghost_idx", Fields: []*irpb.IndexField{{Name: "ghost"}}},
		},
	}
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	_, _, err := (postgres.Emitter{}).EmitOp(op)
	if err == nil {
		t.Fatal("expected err for unknown index field, got nil")
	}
}

// TestSchemaNamespaceEmit — SCHEMA namespace (D19) prepends `schema.`
// to every identifier reference (CREATE TABLE, DROP TABLE, DROP INDEX,
// DROP TYPE, CREATE TYPE). Exercises qualifiedTable + qualifiedIdentifier
// SCHEMA branches; fixtures exercise PREFIX and NONE, this catches the
// SCHEMA path without a full golden.
func TestSchemaNamespaceEmit(t *testing.T) {
	table := &irpb.Table{
		Name:          "reports",
		NamespaceMode: irpb.NamespaceMode_NAMESPACE_MODE_SCHEMA,
		Namespace:     "reporting",
		Columns: []*irpb.Column{
			{Name: "id", ProtoName: "id", Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID, Pk: true},
		},
		PrimaryKey: []string{"id"},
		Indexes: []*irpb.Index{
			{Name: "reports_name_idx", Fields: []*irpb.IndexField{{Name: "id"}}},
		},
	}
	op := &planpb.Op{Variant: &planpb.Op_AddTable{AddTable: &planpb.AddTable{Table: table}}}
	up, down, err := (postgres.Emitter{}).EmitOp(op)
	if err != nil {
		t.Fatalf("EmitOp: %v", err)
	}
	if !strings.Contains(up, "CREATE TABLE reporting.reports") {
		t.Errorf("SCHEMA up missing qualified table:\n%s", up)
	}
	if !strings.Contains(down, "DROP TABLE IF EXISTS reporting.reports") {
		t.Errorf("SCHEMA down missing qualified DROP TABLE:\n%s", down)
	}
	if !strings.Contains(down, "DROP INDEX IF EXISTS reporting.reports_name_idx") {
		t.Errorf("SCHEMA down missing qualified DROP INDEX:\n%s", down)
	}
}

// ---- helpers ----

func runPipeline(t *testing.T, protoPath string) (up, down string) {
	t.Helper()
	base, file := filepath.Split(protoPath)
	lf, err := loader.Load(context.Background(), file, []string{base, protoImportPath})
	if err != nil {
		t.Fatalf("loader.Load: %v", err)
	}
	schema, err := ir.Build(lf)
	if err != nil {
		t.Fatalf("ir.Build: %v", err)
	}
	p, err := plan.Diff(nil, schema)
	if err != nil {
		t.Fatalf("plan.Diff: %v", err)
	}
	up, down, err = emit.Emit(postgres.Emitter{}, p)
	if err != nil {
		t.Fatalf("emit.Emit: %v", err)
	}
	return up, down
}

func mustContain(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("missing: %q\n\nin:\n%s", needle, haystack)
	}
}
