BEGIN;

CREATE TYPE posts_status AS ENUM ('DRAFT', 'PUBLISHED');

CREATE TABLE posts (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status posts_status NOT NULL
);

COMMENT ON TABLE posts IS 'NEW — table with ENUM column forces CREATE TYPE prelude inside AddTable.';

COMMIT;
