BEGIN;

CREATE TABLE events (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    starts_on DATE NOT NULL DEFAULT CURRENT_DATE,
    starts_at_time TIME NOT NULL DEFAULT CURRENT_TIME,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    timeout INTERVAL NOT NULL
);

COMMENT ON TABLE events IS 'Grand-tour fixture: every temporal (carrier, type) cell of D2 plus
all three shapes of default_auto: NOW (DATE → CURRENT_DATE, TIME →
CURRENT_TIME, DATETIME → NOW()). google.protobuf.Duration maps to
INTERVAL with no default_auto support in iter-1 — column stays bare.';

COMMIT;
