package engine_test

// D38 integration tests — engine.Plan on a default identity
// transition, exercising:
//   (1) identity_add (prev nil → curr AUTO_IDENTITY) → AlterColumn
//       with DefaultChange; emit renders ADD GENERATED + setval.
//   (2) identity_drop (prev AUTO_IDENTITY → curr nil) → AlterColumn;
//       emit renders DROP IDENTITY + down recreates via setval.
//   (3) Wrong strategy on identity_add → hard-error.
//   (4) auto_kind_change (AUTO_NOW → literal) — in-axis FactChange,
//       no Finding, emitter handles sem-type via real column.

import (
	"strings"
	"testing"

	"github.com/MrS1lentcz/wandering-compiler/srcgo/domains/compiler/engine"
	irpb "github.com/MrS1lentcz/wandering-compiler/srcgo/pb/domains/compiler/types/ir"
	planpb "github.com/MrS1lentcz/wandering-compiler/srcgo/pb/domains/compiler/types/plan"
)

func mkIdentityBaseSchema(def *irpb.Default) *irpb.Schema {
	col := &irpb.Column{
		Name: "id", ProtoName: "id", FieldNumber: 1,
		Carrier: irpb.Carrier_CARRIER_INT64,
		Type:    irpb.SemType_SEM_ID,
		DbType:  irpb.DbType_DBT_BIGINT,
		Pk:      true,
		Default: def,
	}
	return &irpb.Schema{Tables: []*irpb.Table{{
		Name: "accounts", MessageFqn: "shop.Account",
		Columns: []*irpb.Column{
			col,
			{Name: "email", ProtoName: "email", FieldNumber: 2,
				Carrier: irpb.Carrier_CARRIER_STRING, Type: irpb.SemType_SEM_TEXT},
		},
		PrimaryKey: []string{"id"},
	}}}
}

func TestPlan_DefaultIdentityAdd_NeedsConfirm(t *testing.T) {
	cls := testClassifier(t)
	prev := mkIdentityBaseSchema(nil)
	curr := mkIdentityBaseSchema(&irpb.Default{Variant: &irpb.Default_Auto{Auto: irpb.AutoKind_AUTO_IDENTITY}})

	probe, err := engine.Plan(prev, curr, cls, nil, pgOnlyEmitter)
	if err != nil {
		t.Fatalf("probe: %v", err)
	}
	if len(probe.Findings) != 1 {
		t.Fatalf("want 1 finding, got %d", len(probe.Findings))
	}
	f := probe.Findings[0]
	if f.GetAxis() != "default_identity_add" {
		t.Fatalf("want axis default_identity_add, got %s", f.GetAxis())
	}
	if f.GetProposed() != planpb.Strategy_NEEDS_CONFIRM {
		t.Fatalf("want Proposed=NEEDS_CONFIRM, got %s", f.GetProposed())
	}

	res := []*planpb.Resolution{{
		FindingId: f.GetId(),
		Strategy:  planpb.Strategy_NEEDS_CONFIRM,
		Actor:     "test",
	}}
	plan, err := engine.Plan(prev, curr, cls, res, pgOnlyEmitter)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	up := plan.Migrations[0].GetUpSql()
	for _, frag := range []string{
		"ALTER TABLE accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;",
		"SELECT setval(pg_get_serial_sequence('accounts', 'id'), COALESCE((SELECT MAX(id) FROM accounts), 1), true);",
	} {
		if !strings.Contains(up, frag) {
			t.Errorf("up missing fragment %q\n---\n%s", frag, up)
		}
	}
	down := plan.Migrations[0].GetDownSql()
	if !strings.Contains(down, "ALTER TABLE accounts ALTER COLUMN id DROP IDENTITY;") {
		t.Errorf("down missing DROP IDENTITY:\n%s", down)
	}
}

func TestPlan_DefaultIdentityDrop_NeedsConfirm(t *testing.T) {
	cls := testClassifier(t)
	prev := mkIdentityBaseSchema(&irpb.Default{Variant: &irpb.Default_Auto{Auto: irpb.AutoKind_AUTO_IDENTITY}})
	curr := mkIdentityBaseSchema(nil)

	probe, err := engine.Plan(prev, curr, cls, nil, pgOnlyEmitter)
	if err != nil {
		t.Fatalf("probe: %v", err)
	}
	if len(probe.Findings) != 1 || probe.Findings[0].GetAxis() != "default_identity_drop" {
		t.Fatalf("want 1 default_identity_drop finding, got %v", probe.Findings)
	}

	res := []*planpb.Resolution{{
		FindingId: probe.Findings[0].GetId(),
		Strategy:  planpb.Strategy_NEEDS_CONFIRM,
		Actor:     "test",
	}}
	plan, err := engine.Plan(prev, curr, cls, res, pgOnlyEmitter)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	up := plan.Migrations[0].GetUpSql()
	if !strings.Contains(up, "ALTER TABLE accounts ALTER COLUMN id DROP IDENTITY;") {
		t.Errorf("up missing DROP IDENTITY:\n%s", up)
	}
	down := plan.Migrations[0].GetDownSql()
	for _, frag := range []string{
		"ALTER TABLE accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;",
		"SELECT setval(pg_get_serial_sequence('accounts', 'id'), COALESCE((SELECT MAX(id) FROM accounts), 1), true);",
	} {
		if !strings.Contains(down, frag) {
			t.Errorf("down missing fragment %q\n---\n%s", frag, down)
		}
	}
}

func TestPlan_DefaultIdentityAdd_WrongStrategyHardErrors(t *testing.T) {
	cls := testClassifier(t)
	prev := mkIdentityBaseSchema(nil)
	curr := mkIdentityBaseSchema(&irpb.Default{Variant: &irpb.Default_Auto{Auto: irpb.AutoKind_AUTO_IDENTITY}})

	probe, _ := engine.Plan(prev, curr, cls, nil, pgOnlyEmitter)
	res := []*planpb.Resolution{{
		FindingId: probe.Findings[0].GetId(),
		Strategy:  planpb.Strategy_DROP_AND_CREATE,
		Actor:     "test",
	}}
	_, err := engine.Plan(prev, curr, cls, res, pgOnlyEmitter)
	if err == nil {
		t.Fatal("want hard-error on DROP_AND_CREATE resolution")
	}
	if !strings.Contains(err.Error(), "only NEEDS_CONFIRM") {
		t.Errorf("err should name NEEDS_CONFIRM, got: %v", err)
	}
}

// TestPlan_DefaultIdentityAdd_OverPriorLiteralDefault — prev has a
// literal default that must be dropped before ADD GENERATED. Down
// must restore the prior literal alongside DROP IDENTITY.
func TestPlan_DefaultIdentityAdd_OverPriorLiteralDefault(t *testing.T) {
	cls := testClassifier(t)
	prev := mkIdentityBaseSchema(&irpb.Default{Variant: &irpb.Default_LiteralInt{LiteralInt: 100}})
	curr := mkIdentityBaseSchema(&irpb.Default{Variant: &irpb.Default_Auto{Auto: irpb.AutoKind_AUTO_IDENTITY}})

	probe, _ := engine.Plan(prev, curr, cls, nil, pgOnlyEmitter)
	res := []*planpb.Resolution{{
		FindingId: probe.Findings[0].GetId(),
		Strategy:  planpb.Strategy_NEEDS_CONFIRM,
		Actor:     "test",
	}}
	plan, err := engine.Plan(prev, curr, cls, res, pgOnlyEmitter)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	up := plan.Migrations[0].GetUpSql()
	for _, frag := range []string{
		"ALTER TABLE accounts ALTER COLUMN id DROP DEFAULT;",
		"ALTER TABLE accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;",
	} {
		if !strings.Contains(up, frag) {
			t.Errorf("up missing %q\n---\n%s", frag, up)
		}
	}
	// Order check on the post-BEGIN body so the risk header comments
	// (which mention "ADD GENERATED" in rationale text) don't confuse
	// strings.Index.
	body := up
	if i := strings.Index(body, "BEGIN;"); i >= 0 {
		body = body[i:]
	}
	dropIdx := strings.Index(body, "DROP DEFAULT")
	addIdx := strings.Index(body, "ADD GENERATED")
	if dropIdx < 0 || addIdx < 0 || dropIdx > addIdx {
		t.Errorf("DROP DEFAULT must precede ADD GENERATED in body (PG rejects mixed); body:\n%s", body)
	}
	down := plan.Migrations[0].GetDownSql()
	for _, frag := range []string{
		"ALTER TABLE accounts ALTER COLUMN id DROP IDENTITY;",
		"ALTER TABLE accounts ALTER COLUMN id SET DEFAULT 100;",
	} {
		if !strings.Contains(down, frag) {
			t.Errorf("down missing %q\n---\n%s", frag, down)
		}
	}
}

// TestPlan_DefaultIdentityDrop_WithReplacementLiteral — curr carries
// a replacement literal default after DROP IDENTITY. Down must drop
// the new literal first, then ADD GENERATED + setval.
func TestPlan_DefaultIdentityDrop_WithReplacementLiteral(t *testing.T) {
	cls := testClassifier(t)
	prev := mkIdentityBaseSchema(&irpb.Default{Variant: &irpb.Default_Auto{Auto: irpb.AutoKind_AUTO_IDENTITY}})
	curr := mkIdentityBaseSchema(&irpb.Default{Variant: &irpb.Default_LiteralInt{LiteralInt: 42}})

	probe, _ := engine.Plan(prev, curr, cls, nil, pgOnlyEmitter)
	res := []*planpb.Resolution{{
		FindingId: probe.Findings[0].GetId(),
		Strategy:  planpb.Strategy_NEEDS_CONFIRM,
		Actor:     "test",
	}}
	plan, err := engine.Plan(prev, curr, cls, res, pgOnlyEmitter)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	up := plan.Migrations[0].GetUpSql()
	for _, frag := range []string{
		"ALTER TABLE accounts ALTER COLUMN id DROP IDENTITY;",
		"ALTER TABLE accounts ALTER COLUMN id SET DEFAULT 42;",
	} {
		if !strings.Contains(up, frag) {
			t.Errorf("up missing %q\n---\n%s", frag, up)
		}
	}
	down := plan.Migrations[0].GetDownSql()
	for _, frag := range []string{
		"ALTER TABLE accounts ALTER COLUMN id DROP DEFAULT;",
		"ALTER TABLE accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;",
	} {
		if !strings.Contains(down, frag) {
			t.Errorf("down missing %q\n---\n%s", frag, down)
		}
	}
	body := down
	if i := strings.Index(body, "BEGIN;"); i >= 0 {
		body = body[i:]
	}
	dropIdx := strings.Index(body, "DROP DEFAULT")
	addIdx := strings.Index(body, "ADD GENERATED")
	if dropIdx < 0 || addIdx < 0 || dropIdx > addIdx {
		t.Errorf("DROP DEFAULT must precede ADD GENERATED in down body too; body:\n%s", body)
	}
}

// TestPlan_AutoKindChange_InAxis — AUTO_NOW → literal on DATETIME.
// In-axis SAFE (no Finding); emitter renders SET DEFAULT with the
// sem-type-correct autoExpr.
func TestPlan_AutoKindChange_InAxis(t *testing.T) {
	cls := testClassifier(t)
	mk := func(def *irpb.Default) *irpb.Schema {
		return &irpb.Schema{Tables: []*irpb.Table{{
			Name: "events", MessageFqn: "tg.Event",
			Columns: []*irpb.Column{
				{Name: "id", ProtoName: "id", FieldNumber: 1,
					Carrier: irpb.Carrier_CARRIER_INT64, Type: irpb.SemType_SEM_ID,
					DbType: irpb.DbType_DBT_BIGINT, Pk: true},
				{Name: "recorded_at", ProtoName: "recorded_at", FieldNumber: 2,
					Carrier: irpb.Carrier_CARRIER_TIMESTAMP, Type: irpb.SemType_SEM_DATETIME,
					Default: def},
			},
			PrimaryKey: []string{"id"},
		}}}
	}
	prev := mk(&irpb.Default{Variant: &irpb.Default_Auto{Auto: irpb.AutoKind_AUTO_NOW}})
	curr := mk(&irpb.Default{Variant: &irpb.Default_LiteralString{LiteralString: "1970-01-01 00:00:00"}})

	plan, err := engine.Plan(prev, curr, cls, nil, pgOnlyEmitter)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(plan.Findings) != 0 {
		t.Fatalf("auto_kind_change should be in-axis SAFE, got findings: %v", plan.Findings)
	}
	up := plan.Migrations[0].GetUpSql()
	if !strings.Contains(up, "ALTER TABLE events ALTER COLUMN recorded_at SET DEFAULT '1970-01-01 00:00:00';") {
		t.Errorf("up missing literal SET DEFAULT:\n%s", up)
	}
	down := plan.Migrations[0].GetDownSql()
	if !strings.Contains(down, "ALTER TABLE events ALTER COLUMN recorded_at SET DEFAULT NOW();") {
		t.Errorf("down should restore NOW() (sem-type-driven):\n%s", down)
	}
}
