BEGIN;

CREATE TABLE attachments (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_path TEXT NOT NULL,
    report_path TEXT NOT NULL,
    anything_path TEXT NOT NULL,
    cover_image TEXT NOT NULL,
    thumbnail TEXT NOT NULL,
    CONSTRAINT attachments_script_path_blank CHECK (script_path <> ''),
    CONSTRAINT attachments_report_path_blank CHECK (report_path <> ''),
    CONSTRAINT attachments_report_path_format CHECK (report_path ~ '(?i)\.(csv|json|xml)$'),
    CONSTRAINT attachments_anything_path_blank CHECK (anything_path <> ''),
    CONSTRAINT attachments_cover_image_blank CHECK (cover_image <> ''),
    CONSTRAINT attachments_cover_image_format CHECK (cover_image ~ '(?i)\.(jpg|jpeg|png|gif|webp|avif|svg)$'),
    CONSTRAINT attachments_thumbnail_blank CHECK (thumbnail <> ''),
    CONSTRAINT attachments_thumbnail_format CHECK (thumbnail ~ '(?i)\.(jpg|jpeg|png|webp)$')
);

COMMENT ON COLUMN attachments.script_path IS 'Executable / directory / pipe — any suffix, blank CHECK only.';
COMMENT ON COLUMN attachments.report_path IS 'Concrete list — regex emits (?i)\.(csv|json|xml)$ CHECK.';
COMMENT ON COLUMN attachments.anything_path IS 'Wildcard — CHECK disabled, blank only.';
COMMENT ON COLUMN attachments.cover_image IS 'IMAGE_PATH default extensions.';
COMMENT ON COLUMN attachments.thumbnail IS 'IMAGE_PATH with author override — raster-only, no svg.';

COMMIT;
