CREATE TABLE products (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    CONSTRAINT products_sku_blank CHECK (sku <> ''),
    CONSTRAINT products_title_blank CHECK (title <> '')
);

CREATE UNIQUE INDEX products_sku_uidx ON products (sku);

CREATE TABLE tags (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    CONSTRAINT tags_name_blank CHECK (name <> ''),
    CONSTRAINT tags_name_format CHECK (name ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE UNIQUE INDEX tags_name_uidx ON tags (name);

CREATE TABLE product_tags (
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
);
