BEGIN;

CREATE TABLE dashboard_url_field (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    href VARCHAR(2048) NOT NULL,
    CONSTRAINT dashboard_url_field_href_blank CHECK (href <> ''),
    CONSTRAINT dashboard_url_field_href_format CHECK (href ~ '^https?://.+$')
);

CREATE TABLE product (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(40) NOT NULL,
    CONSTRAINT product_sku_blank CHECK (sku <> '')
);

CREATE UNIQUE INDEX product_sku_uidx ON product (sku);

CREATE TABLE product_category (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    label VARCHAR(80) NOT NULL,
    CONSTRAINT product_category_label_blank CHECK (label <> '')
);

CREATE TABLE ye_olde_profiles (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT ye_olde_profiles_name_blank CHECK (name <> '')
);

COMMIT;
